# DSA4156 Lab: Inmon vs. Kimball on Sample Superstore
## Template notebook

| | |
|---|---|
| **Group name** | *fill in* |
| **Members** | *fill in* |

You will build two data warehouses from the same source data, in one PostgreSQL database:

- `staging`: raw and cleaned copies of the source files
- `inmon`: a **3NF** enterprise warehouse
- `kimball`: a **denormalized** dimensional model (star or snowflake schema)

**Rules**
- Cells marked `# TODO` are yours to complete. You may add as many cells as you need.
- You may transform with pandas, SQL, or both, but every step must run from this notebook.
- Before submitting, run **Kernel > Restart & Run All** and save the notebook *with outputs*.
- Your data model diagrams go in the PDF report, not here.

## 0. Setup

**Requirements**
- PostgreSQL **15 or newer** (16 recommended). Version 15 is needed for `UNIQUE NULLS NOT DISTINCT`.
- Python packages: `pandas`, `sqlalchemy>=2.0`, `psycopg2-binary`

Create an empty database first, for example in `psql`:
```sql
CREATE DATABASE superstore_dw;
```
Then set your connection string below, or set the `DW_URL` environment variable.
**Do not commit real passwords** in the notebook you submit.

In [ ]:
import os, re
from pathlib import Path

import numpy as np
import pandas as pd
from sqlalchemy import create_engine, text
from sqlalchemy import types as sa_types

DATA_DIR = Path("data")
DW_URL = os.getenv("DW_URL", "postgresql+psycopg2://postgres:password@localhost:5432/superstore_dw")

engine = create_engine(DW_URL, future=True)

def run_sql(sql: str) -> None:
    """Execute one or more SQL statements (DDL or DML) in a single transaction."""
    with engine.begin() as conn:
        conn.exec_driver_sql(sql)

def q(sql: str, **params) -> pd.DataFrame:
    """Run a SELECT and return the result as a DataFrame."""
    with engine.connect() as conn:
        return pd.read_sql(text(sql), conn, params=params)

def table_counts(schema: str) -> pd.DataFrame:
    """Row count of every table (partitioned parents included, partitions excluded) in a schema."""
    tables = q("""
        SELECT c.relname AS table_name
        FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = :s AND c.relkind IN ('r', 'p') AND NOT c.relispartition
        ORDER BY 1""", s=schema)["table_name"]
    rows = [(t, int(q(f'SELECT count(*) AS n FROM "{schema}"."{t}"')["n"][0])) for t in tables]
    return pd.DataFrame(rows, columns=["table_name", "row_count"])

print(q("SELECT version()")["version"][0])

PostgreSQL 18.6 on x86_64-windows, compiled by msvc-19.44.35228, 64-bit

## 1. Extract

The source system gave us three files (originally three sheets of one workbook):

| File | Contents |
|---|---|
| `orders.csv` | One row per order line (flat, denormalized, 21 columns) |
| `returns.csv` | Orders that were returned |
| `people.csv` | The regional manager of each region |

We read everything **as text** so that nothing is silently converted, then copy the raw data into a
`staging` schema. Staging keeps an untouched copy of the source so the warehouse can always be rebuilt.

In [39]:
raw_orders  = pd.read_csv(DATA_DIR / "orders.csv",  dtype=str, keep_default_na=False)
raw_returns = pd.read_csv(DATA_DIR / "returns.csv", dtype=str, keep_default_na=False)
raw_people  = pd.read_csv(DATA_DIR / "people.csv",  dtype=str, keep_default_na=False)

def snake(col: str) -> str:
    return re.sub(r"[^0-9a-z]+", "_", col.strip().lower()).strip("_")

run_sql("CREATE SCHEMA IF NOT EXISTS staging;")
for name, df in [("orders_raw", raw_orders), ("returns_raw", raw_returns), ("people_raw", raw_people)]:
    df.rename(columns=snake).to_sql(name, engine, schema="staging", if_exists="replace", index=False)

print({n: len(d) for n, d in [("orders", raw_orders), ("returns", raw_returns), ("people", raw_people)]})
raw_orders.head()

{'orders': 9994, 'returns': 800, 'people': 4}

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2017-152156,11/8/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0,41.9136
1,2,CA-2017-152156,11/8/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0,219.582
2,3,CA-2017-138688,6/12/2017,6/16/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0,6.8714
3,4,US-2016-108966,10/11/2016,10/18/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.031
4,5,US-2016-108966,10/11/2016,10/18/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.368,2,0.2,2.5164

In [40]:
raw_orders['Order ID'].duplicated().sum()

np.int64(4985)

### 1.1 Profile the source: find the functional dependencies

Before designing any model, test which columns determine which. `A -> B` holds when every value of `A`
maps to exactly one value of `B`. The count below is the number of `A` values that break the rule.
These results are the evidence for your normalization decisions in the report.

### **Check Data Types**

In [41]:
orders = raw_orders.rename(columns=snake)
people = raw_people.rename(columns=snake)
returns_df = raw_returns.rename(columns=snake)

In [42]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   row_id         9994 non-null   str
 1   order_id       9994 non-null   str
 2   order_date     9994 non-null   str
 3   ship_date      9994 non-null   str
 4   ship_mode      9994 non-null   str
 5   customer_id    9994 non-null   str
 6   customer_name  9994 non-null   str
 7   segment        9994 non-null   str
 8   country        9994 non-null   str
 9   city           9994 non-null   str
 10  state          9994 non-null   str
 11  postal_code    9994 non-null   str
 12  region         9994 non-null   str
 13  product_id     9994 non-null   str
 14  category       9994 non-null   str
 15  sub_category   9994 non-null   str
 16  product_name   9994 non-null   str
 17  sales          9994 non-null   str
 18  quantity       9994 non-null   str
 19  discount       9994 non-null   str
 20  profit         9994 non-null   str
dtypes: str(21)
memory usage: 1.6 MB

In [43]:
orders.isna().sum()

row_id           0
order_id         0
order_date       0
ship_date        0
ship_mode        0
customer_id      0
customer_name    0
segment          0
country          0
city             0
state            0
postal_code      0
region           0
product_id       0
category         0
sub_category     0
product_name     0
sales            0
quantity         0
discount         0
profit           0
dtype: int64

In [44]:
len(orders[(orders['city'] == 'Burlington') & (orders['state'] == 'Vermont')])

11

In [45]:
orders[(orders['city'] == 'Burlington') & (orders['state'] == 'Vermont')].T

,2234,5274,8798,9146,9147,9148,9386,9387,9388,9389,9741
row_id,2235,5275,8799,9147,9148,9149,9387,9388,9389,9390,9742
order_id,CA-2018-104066,CA-2016-162887,US-2017-150140,US-2017-165505,US-2017-165505,US-2017-165505,US-2018-127292,US-2018-127292,US-2018-127292,US-2018-127292,CA-2016-117086
order_date,12/5/2018,11/7/2016,4/6/2017,1/23/2017,1/23/2017,1/23/2017,1/19/2018,1/19/2018,1/19/2018,1/19/2018,11/8/2016
ship_date,12/10/2018,11/9/2016,4/10/2017,1/27/2017,1/27/2017,1/27/2017,1/23/2018,1/23/2018,1/23/2018,1/23/2018,11/12/2016
ship_mode,Standard Class,Second Class,Standard Class,Standard Class,Standard Class,Standard Class,Standard Class,Standard Class,Standard Class,Standard Class,Standard Class
customer_id,QJ-19255,SV-20785,VM-21685,CB-12535,CB-12535,CB-12535,RM-19375,RM-19375,RM-19375,RM-19375,QJ-19255
customer_name,Quincy Jones,Stewart Visinsky,Valerie Mitchum,Claudia Bergmann,Claudia Bergmann,Claudia Bergmann,Raymond Messe,Raymond Messe,Raymond Messe,Raymond Messe,Quincy Jones
segment,Corporate,Consumer,Home Office,Corporate,Corporate,Corporate,Consumer,Consumer,Consumer,Consumer,Corporate
country,United States,United States,United States,United States,United States,United States,United States,United States,United States,United States,United States
city,Burlington,Burlington,Burlington,Burlington,Burlington,Burlington,Burlington,Burlington,Burlington,Burlington,Burlington
state,Vermont,Vermont,Vermont,Vermont,Vermont,Vermont,Vermont,Vermont,Vermont,Vermont,Vermont
postal_code,,,,,,,,,,,
region,East,East,East,East,East,East,East,East,East,East,East
product_id,TEC-AC-10001013,FUR-CH-10000595,TEC-PH-10002555,TEC-AC-10002926,OFF-AR-10003477,OFF-ST-10001526,OFF-PA-10000157,OFF-PA-10001970,OFF-AP-10000828,OFF-EN-10001509,FUR-BO-10004834
category,Technology,Furniture,Technology,Technology,Office Supplies,Office Supplies,Office Supplies,Office Supplies,Office Supplies,Office Supplies,Furniture
sub_category,Accessories,Chairs,Phones,Accessories,Art,Storage,Paper,Paper,Appliances,Envelopes,Bookcases
product_name,Logitech ClearChat Comfort/USB Headset H390,Safco Contoured Stacking Chairs,Nortel Meridian M5316 Digital phone,Logitech Wireless Marathon Mouse M705,4009 Highlighters,Iceberg Mobile Mega Data/Printer Cart,Xerox 191,Xerox 1881,Avanti 4.4 Cu. Ft. Refrigerator,Poly String Tie Envelopes,"Riverside Palais Royal Lawyers Bookcase, Royal..."
sales,205.03,715.2,1294.75,99.98,8.04,1564.29,79.92,12.28,542.94,2.04,4404.9
quantity,7,3,5,2,6,13,4,1,3,1,5
discount,0,0,0,0,0,0,0,0,0,0,0
profit,67.6599,178.8,336.635,42.9914,2.7336,406.7154,37.5624,5.7716,152.0232,0.9588,1013.127

We have observed that the null values for postal_code are all from Burlington, Vermont. According to codigo-postal.co, the standard postal code for Burlington, Vermont is 05401, hence we fill the null values with it. 


Reference: https://codigo-postal.co/en-us/usa/vermont/burlington/

In [46]:
orders['postal_code'].fillna('05401', inplace=True)

C:\Users\L\AppData\Local\Temp\ipykernel_18644\1312218500.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  orders['postal_code'].fillna('05401', inplace=True)

0       42420
1       42420
2       90036
3       33311
4       33311
5       90032
6       90032
7       90032
8       90032
9       90032
10      90032
11      90032
12      28027
13      98103
14      76106
15      76106
16      53711
17      84084
18      94109
19      94109
20      94109
21      68025
22      68025
23      19140
24      84057
25      90049
26      90049
27      19140
28      19140
29      19140
30      19140
31      19140
32      19140
33      19140
34      77095
35      75080
36      75080
37      77041
38      77041
39      77041
40      77041
41      60540
42      90049
43      32935
44      55122
45      55122
46      48185
47      19901
48      19901
49      47150
50      47150
51      47150
52      47150
53      10024
54      10024
55      12180
56      12180
57      12180
58      12180
59      12180
60      12180
61      12180
62      90004
63      90004
64      90004
65      90004
66      60610
67      85234
68      85234
69      22153
70      10009
71      49201
72      38109
73      38109
74      38109
75      77041
76      77041
77      77041
78      77070
79      35601
80      35601
81      94122
82      94122
83      27707
84      60623
85      29203
86      55901
87      55901
88      77095
89      90036
90      90036
91      90036
92      55407
93      55407
94      55407
95      97206
96      10009
97      94122
98      55106
99      60610
100     60610
101     60610
102     55901
103     80013
104     80013
105     80013
106     28205
107     28205
108     28205
109     60462
110     10035
111     50322
112     50322
113     43229
114     43229
115     43229
116     43229
117     98103
118     37620
119     19805
120     19805
121     19805
122     19805
123     19805
124     77041
125     61701
126     85023
127     85023
128     90004
129     90004
130     43229
131     43229
132     43229
133     95661
134     95661
135     95661
136     95661
137     95661
138     95661
139     95661
140     19140
141     94122
142     94122
143     94122
144     64055
145     91104
146     43055
147     53132
148     53132
149     53132
150     53132
151     85254
152     85254
153     95123
154     95123
155     95123
156     98105
157     98115
158     73034
159     73034
160     90045
161     19134
162     88220
163     98115
164     78207
165     78207
166     78207
167     78207
168     78207
169     78207
170     78207
171     90004
172     90004
173     90004
174     60623
175     60623
176     77036
177     43055
178     43055
179     10009
180     62521
181     62521
182     71203
183     71203
184     71203
185      6824
186     90032
187     75051
188     75051
189     10035
190     10035
191     10035
192     10035
193     10035
194     92374
195     45011
196     45011
197      7090
198     19120
199     19120
200     44312
201     80219
202     80219
203     75220
204     37064
205     90604
206     48601
207     48601
208     48601
209     48601
210     48601
211     75220
212     44256
213     44256
214     44256
215     44256
216     44256
217     90032
218     90032
219     43017
220     43017
221     43017
222     43017
223     43017
224     43017
225     48227
226     48227
227     48227
228     38401
229     38401
230     28205
231     33614
232     33614
233     33614
234     33614
235     33614
236     95051
237     60610
238     60610
239     60610
240     60610
241     60610
242     60610
243     60610
244     55044
245     55044
246     55044
247     55044
248     55044
249     94109
250     92037
251     92037
252     10024
253     10024
254     60623
255     60623
256     60623
257     60623
258     10009
259     10009
260     10009
261     77506
262     77036
263     77036
264     60610
265     94513
266     27514
267      7960
268     45231
269     45231
270     94110
271     94109
272     94109
273     94109
274     90301
275     90301
276     19140
277     19140
278     19140
279     19140
280     77070
281     77070
282     90004
283     97206
284     97206
285     97206
286     33319
287     33319
288     33319
289     43229
290     43229
291     43229
292     43229
293     80906
294     80906
295     80906
296     80906
297     80906
298      7109
299      7109
300      7109
301      7109
302      7109
303     60623
304     10024
305     48180
306      8701
307      8701
308     22204
309     80004
310     80004
311     80004
312     80004
313      7601
314     33710
315     33710
316     19143
317     10024
318     10024
319     10024
320     10024
321     10024
322     90805
323     92345
324     92345
325     37130
326     19143
327     19143
328     19143
329     19143
330     19143
331     19134
332     19134
333     19134
334     90045
335     90045
336     90045
337     94122
338     94122
339     84041
340     19140
341     19140
342     19140
343     19140
344     78745
345     94122
346      1852
347      1852
348      1852
349     10009
350     10009
351     10009
352     10009
353     10009
354     10035
355     10035
356     10035
357     10035
358     28205
359     31907
360     31907
361     10009
362     10009
363     10009
364     10009
365     94109
366      6040
367      6040
368      6040
369      6040
370     78550
371     78550
372     85705
373     85705
374     85705
375     85705
376     62301
377      2038
378     77095
379     77095
380     77095
381     94109
382     94109
383     48180
384     33024
385     33024
386     19140
387     19140
388     45231
389     10009
390     10009
391     98198
392     98198
393     61604
394     89115
395      2886
396      2886
397     49201
398     77036
399     77036
400     77036
401     77036
402     33180
403     28403
404     10024
405     94110
406     94110
407     94110
408     94110
409     94110
410     94110
411     94110
412     94110
413     94110
414     98105
415     98105
416     92646
417     90004
418     40475
419     90045
420     90045
421     80027
422      1841
423      1841
424     39212
425     48187
426     48187
427     10801
428     78207
429     28052
430     28052
431     28052
432     28052
433      1852
434     32216
435     32216
436     60623
437     60623
438     77070
439     10024
440     48227
441     48227
442     48227
443     48227
444     48227
445     48227
446     47201
447     13021
448     13021
449     13021
450     13021
451     13021
452     13021
453     44312
454     44312
455     73071
456     94521
457     62521
458     62521
459     98115
460     98115
461     98115
462     85023
463     85023
464     85023
465     85023
466     85023
467     60068
468     79109
469     60610
470     11757
471     94110
472     94110
473     94110
474     94110
475     94110
476     94110
477     90008
478     12180
479     10024
480     10024
481     92024
482     10024
483     10024
484     90045
485     90045
486     90045
487     60610
488     77340
489     77340
490     77340
491     14609
492     14609
493     98115
494     38109
495     72701
496     92627
497     92627
498     92627
499     92627
500     80134
501     80134
502     80134
503     80134
504     80134
505     10024
506     30318
507     30318
508     30318
509     30318
510     64118
511     64118
512     43055
513     90049
514     90049
515     59405
516     59405
517     59405
518     59405
519     77041
520     77041
521     77041
522     48234
523     90032
524     90032
525      1841
526     33801
527     33801
528     19134
529     19134
530     19134
531     90036
532     90032
533     36116
534     36116
535     85204
536     60653
537     10009
538     42420
539     42420
540     54302
541     85705
542     45503
543     76106
544     76106
545     76106
546     10035
547     10035
548     60653
549     60653
550     60653
551     94110
552     32216
553     77070
554     92804
555     28403
556     90045
557     90045
558     90045
559     94110
560     94110
561     33614
562     33614
563     98105
564     98105
565     90008
566     98105
567     98105
568     98105
569     98105
570     10024
571     10024
572     10024
573     10024
574     98270
575     90805
576     90805
577     90805
578     60610
579     60610
580     90004
581     80219
582     80219
583     80219
584     80219
585     80219
586     40475
587     40475
588     97301
589     97301
590     97301
591     97301
592     78041
593     78041
594     92024
595     92024
596     92024
597     92024
598     19134
599     19120
600     19120
601     19120
602     33614
603     33614
604     33614
605     33614
606     33614
607     19134
608     19134
609     19134
610     75217
611     75217
612     19143
613     19143
614     43123
615     43123
616     10011
617     10011
618     10011
619     10011
620     10011
621     60610
622     48126
623     48126
624     48126
625     48126
626     10009
627     98115
628     94122
629     94122
630     80013
631     80013
632     80013
633     33180
634     33180
635     31088
636     80013
637     80013
638     94591
639     94591
640     55407
641     92691
642     92691
643     48307
644      7060
645     47201
646     85635
647     85635
648     98661
649     98661
650     98661
651     10024
652     10035
653     10035
654     43229
655     43229
656     43229
657     60505
658     60505
659     76017
660     76017
661     76017
662     76017
663     10011
664     40214
665     75081
666     75081
667     75081
668     44105
669     60653
670     60653
671     60653
672     62301
673     47201
674     47201
675     47201
676     75701
677     75701
678     75701
679     75701
680     10024
681     10024
682     10024
683     27217
684     27217
685     39212
686     39212
687     39212
688     10035
689     22980
690     22980
691     22980
692     90036
693     90036
694     19013
695     19013
696     19013
697     19013
698     19013
699     19013
700     19013
701     44105
702     98103
703     90805
704     27511
705     27511
706     27511
707     10035
708     10035
709     10035
710     10035
711     32137
712     10550
713     10550
714     10550
715     98105
716     19901
717     43055
718     84057
719     84057
720     90045
721     48205
722     48205
723     19140
724     33012
725     78745
726     78745
727     11572
728     11572
729     11572
730     11572
731     11572
732     98115
733     98115
734     98115
735     98115
736     98115
737     98115
738     94110
739     60540
740     60540
741     60540
742     75220
743     75220
744     75220
745     75220
746     92105
747     92105
748     60201
749     48183
750     48183
751     48183
752     48183
753     94110
754     90036
755     32216
756     55016
757     55016
758     10009
759     54302
760     90004
761     30318
762     43229
763     71111
764     71111
765     71111
766     71111
767     71111
768     33710
769     22204
770     50315
771     50315
772     50315
773     50315
774     50315
775     50315
776     45231
777     94110
778     94110
779     94110
780     94110
781     43229
782     43229
783     43229
784     43229
785     29203
786     93534
787     93534
788     23223
789     23223
790     23223
791     23223
792     28806
793     94110
794     94110
795     55901
796     14609
797     14609
798     14609
799     92530
800     92105
801     92105
802     10024
803     71203
804     94122
805     80219
806     80219
807     68104
808     68104
809     98026
810     98026
811     98026
812     98026
813     92704
814     92704
815     53209
816     19140
817     19140
818     19140
819     19140
820     19140
821     19140
822      7109
823      7109
824     94110
825     94110
826     55044
827     55044
828     55044
829     41042
830     41042
831     41042
832     41042
833     33614
834     33614
835     33614
836     75701
837     38401
838     76106
839     10035
840     10035
841     10035
842     90036
843     90036
844     90036
845     90036
846     40214
847     40214
848     44052
849      7036
850     93905
851     93905
852     39212
853     10035
854     10035
855     10035
856     10035
857     10035
858      8901
859      8901
860     94122
861     94122
862     32216
863     32216
864     32216
865     22153
866     22153
867     19140
868     17602
869     19143
870     19143
871      3301
872     10009
873     10009
874     28205
875      3301
876      3301
877      3301
878     19120
879     10024
880     10024
881     22153
882     94109
883     48227
884     14609
885     90045
886     92105
887     21044
888     94122
889     10801
890     10801
891     48227
892     48227
893     48227
894     94122
895     94122
896     77095
897     48227
898     13021
899     45503
900     75043
901     75043
902     60653
903     90032
904     90032
905     90032
906     10009
907     10009
908     10009
909     49201
910     49201
911     49201
912      6360
913     53209
914     53209
915     78207
916     78207
917     78207
918     75220
919     75220
920     22304
921     10009
922     10009
923     10009
924     10011
925     19143
926     19143
927     22153
928     22153
929     43615
930     43615
931     43615
932     19140
933     19120
934     19120
935     19120
936     19120
937     87401
938     92503
939     92503
940     94110
941     90503
942     90503
943     98105
944     98105
945     98105
946     85204
947     19120
948     19120
949     19120
950     19120
951     19120
952     19143
953     78664
954     78664
955     39212
956     85023
957     85023
958     85023
959     92054
960     94110
961     72701
962     94110
963     33433
964     10011
965     10011
966     10011
967     10011
968     10011
969     10011
970     19134
971     19134
972     19134
973     19134
974     10011
975     10011
976     97206
977     48205
978     28403
979     47201
980     10035
981     80027
982     80027
983     80027
984     77506
985     77506
986     77506
987     77041
988     13021
989     13021
990     32216
991     10024
992     95123
993     95123
994     23464
995     23464
996     42420
997     42420
998     42420
999     42420
1000    98661
1001    10024
1002    10024
1003    10024
1004    92563
1005    28540
1006    85254
1007    85254
1008    52601
1009    60653
1010    92037
1011    98502
1012    98502
1013    98103
1014    98103
1015    90036
1016    10011
1017    10011
1018    10011
1019    10011
1020    20016
1021    20016
1022    20016
1023    19134
1024    90045
1025    45503
1026    45503
1027    45503
1028     7601
1029     7601
1030     7601
1031     7601
1032     7601
1033    45231
1034    45231
1035    45231
1036    65109
1037    90004
1038    27217
1039    27217
1040    63376
1041    10035
1042    10035
1043    60610
1044    60610
1045    61107
1046    33142
1047    33142
1048    94109
1049    94109
1050    19134
1051    19134
1052    19134
1053    10009
1054    10009
1055    10009
1056    10009
1057    92037
1058    92037
1059    19143
1060    77095
1061    43615
1062    43615
1063    43615
1064    43615
1065    43615
1066    43615
1067    94122
1068    78521
1069    19143
1070    90008
1071    80219
1072    10035
1073    85204
1074    85204
1075    85204
1076    47201
1077    98105
1078    98105
1079    98105
1080    48227
1081    48227
1082    10701
1083    10701
1084    10701
1085    10701
1086    50315
1087    94601
1088    94601
1089    28110
1090    28110
1091    92105
1092    92105
1093    20735
1094    20735
1095    28205
1096    28205
1097    90049
1098    94122
1099    94122
1100    94122
1101    94122
1102    77041
1103    77041
1104    92503
1105    77041
1106    77041
1107    77041
1108    77041
1109    77041
1110    77041
1111    77041
1112    77041
1113    92024
1114    92024
1115    92024
1116    94110
1117    30076
1118    30076
1119    30076
1120    30076
1121    72401
1122    72401
1123    72401
1124    72401
1125    72401
1126    72401
1127    47374
1128    47374
1129    22153
1130    22153
1131    22153
1132    94509
1133    19134
1134    19134
1135    33030
1136    46350
1137    46350
1138    46350
1139    46350
1140    46350
1141    90045
1142    90045
1143    90045
1144    90045
1145    90045
1146    48911
1147    48911
1148    48911
1149    48911
1150    48911
1151    44221
1152    89502
1153    89502
1154    22801
1155    22801
1156    22801
1157    22801
1158    90004
1159    55407
1160    55407
1161    92025
1162    10035
1163    10035
1164    10035
1165    49201
1166    98115
1167    10035
1168    10035
1169    10035
1170    10035
1171    48073
1172    90008
1173    61701
1174    10035
1175     3301
1176    90004
1177    20852
1178    20852
1179    77070
1180     8701
1181     8701
1182    28540
1183    28540
1184    98103
1185    98103
1186    98103
1187    98103
1188    90036
1189    90036
1190    90036
1191    90036
1192    90036
1193    33065
1194    33065
1195    33065
1196    33065
1197    77041
1198    77041
1199    77041
1200    80219
1201    80219
1202    80219
1203    80219
1204    80219
1205    28205
1206    10009
1207    10009
1208    10009
1209    10009
1210    10009
1211    10009
1212    19134
1213    19134
1214    19134
1215    19134
1216    19134
1217    19134
1218    19134
1219    19134
1220    90036
1221    90036
1222    10024
1223    10024
1224    10024
1225    10024
1226    10024
1227    10024
1228    90045
1229    90045
1230    90045
1231    14215
1232    14215
1233    45231
1234    33437
1235    33437
1236    33437
1237    33437
1238    98105
1239    98105
1240    98105
1241    10024
1242    10009
1243    10009
1244    39503
1245    93727
1246    93727
1247    93727
1248    10009
1249    10009
1250    10009
1251    10009
1252    53209
1253    19013
1254    19013
1255    19013
1256    19013
1257    28205
1258    28205
1259    28205
1260    32216
1261    27834
1262    11561
1263    46350
1264    46350
1265    94122
1266    90045
1267    90045
1268    80027
1269    35630
1270    60623
1271    60623
1272    60623
1273    76106
1274    76106
1275    76106
1276    76106
1277    77070
1278    31204
1279    31204
1280    52402
1281    32216
1282    32216
1283    32216
1284    78745
1285     2908
1286    10035
1287    10009
1288    10009
1289    10009
1290    94122
1291    94122
1292    92105
1293    92105
1294    92105
1295    81001
1296    94533
1297    94533
1298    55106
1299    94109
1300    22153
1301    22153
1302    22204
1303    31907
1304    31907
1305    77036
1306    91104
1307    91104
1308    91104
1309    91104
1310    91104
1311     1841
1312     1841
1313    43229
1314    90032
1315    90032
1316    90032
1317    19120
1318    32725
1319    32725
1320    45231
1321    45231
1322    42071
1323    28403
1324     1841
1325    60653
1326    19120
1327     6360
1328    94110
1329    94109
1330    44052
1331    44052
1332    75220
1333    75220
1334    90049
1335     6457
1336    90008
1337    10011
1338    10011
1339    10011
1340    28540
1341    28540
1342    28540
1343    11520
1344    11520
1345    55044
1346    55044
1347    55044
1348    55044
1349    55044
1350    60201
1351    22204
1352    94109
1353    94109
1354    94109
1355    77036
1356    77036
1357    40214
1358    76106
1359    90049
1360    19120
1361    19120
1362    19120
1363    85705
1364    85705
1365    85705
1366    85705
1367    85705
1368    90660
1369    80906
1370    80906
1371    20735
1372    94591
1373    94591
1374    84604
1375    84062
1376    84062
1377    84062
1378    84062
1379    84062
1380    84062
1381    60505
1382    30080
1383    30080
1384    30080
1385    30080
1386    30080
1387    30080
1388    30080
1389    30080
1390    30080
1391    30080
1392    30080
1393    27217
1394    60505
1395    60505
1396    10035
1397    10035
1398    10035
1399    10035
1400    24153
1401    24153
1402    43229
1403    43229
1404    19143
1405    19143
1406    19143
1407    10024
1408    10024
1409    85023
1410    75051
1411    10035
1412    10035
1413    10024
1414    92627
1415    92627
1416    77041
1417    77041
1418    77041
1419    85204
1420    85204
1421    85204
1422    85204
1423    85204
1424    85204
1425    85204
1426    93905
1427    93905

In [47]:
orders.isna().sum()

row_id           0
order_id         0
order_date       0
ship_date        0
ship_mode        0
customer_id      0
customer_name    0
segment          0
country          0
city             0
state            0
postal_code      0
region           0
product_id       0
category         0
sub_category     0
product_name     0
sales            0
quantity         0
discount         0
profit           0
dtype: int64

In [48]:
orders.dropna(subset=['postal_code'], inplace=True)

In [49]:
people.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   regional_manager  4 non-null      str
 1   region            4 non-null      str
dtypes: str(2)
memory usage: 196.0 bytes

In [50]:
returns_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   returned  800 non-null    str
 1   order_id  800 non-null    str
dtypes: str(2)
memory usage: 12.6 KB

In [51]:
returns_df

    returned        order_id
0        Yes  CA-2015-100762
1        Yes  CA-2015-100762
2        Yes  CA-2015-100762
3        Yes  CA-2015-100762
4        Yes  CA-2015-100867
5        Yes  CA-2015-102652
6        Yes  CA-2015-102652
7        Yes  CA-2015-102652
8        Yes  CA-2015-102652
9        Yes  CA-2015-103373
10       Yes  CA-2015-103744
11       Yes  CA-2015-103744
12       Yes  CA-2015-103940
13       Yes  CA-2015-103940
14       Yes  CA-2015-103940
15       Yes  CA-2015-103940
16       Yes  CA-2015-104829
17       Yes  CA-2015-105270
18       Yes  CA-2015-105270
19       Yes  CA-2015-108609
20       Yes  CA-2015-108861
21       Yes  CA-2015-109918
22       Yes  CA-2015-109918
23       Yes  CA-2015-109918
24       Yes  CA-2015-110786
25       Yes  CA-2015-110786
26       Yes  CA-2015-110786
27       Yes  CA-2015-110786
28       Yes  CA-2015-110786
29       Yes  CA-2015-110786
30       Yes  CA-2015-110786
31       Yes  CA-2015-111871
32       Yes  CA-2015-116785
33       Yes  CA-2015-116785
34       Yes  CA-2015-123225
35       Yes  CA-2015-123225
36       Yes  CA-2015-123253
37       Yes  CA-2015-123498
38       Yes  CA-2015-123498
39       Yes  CA-2015-124688
40       Yes  CA-2015-124688
41       Yes  CA-2015-124688
42       Yes  CA-2015-126361
43       Yes  CA-2015-126361
44       Yes  CA-2015-126361
45       Yes  CA-2015-126361
46       Yes  CA-2015-126361
47       Yes  CA-2015-126361
48       Yes  CA-2015-126403
49       Yes  CA-2015-126403
50       Yes  CA-2015-126403
51       Yes  CA-2015-126403
52       Yes  CA-2015-126522
53       Yes  CA-2015-127012
54       Yes  CA-2015-127012
55       Yes  CA-2015-127012
56       Yes  CA-2015-127131
57       Yes  CA-2015-127131
58       Yes  CA-2015-127131
59       Yes  CA-2015-127131
60       Yes  CA-2015-133690
61       Yes  CA-2015-133690
62       Yes  CA-2015-134726
63       Yes  CA-2015-134726
64       Yes  CA-2015-135657
65       Yes  CA-2015-135699
66       Yes  CA-2015-135699
67       Yes  CA-2015-140816
68       Yes  CA-2015-141726
69       Yes  CA-2015-141726
70       Yes  CA-2015-141726
71       Yes  CA-2015-141726
72       Yes  CA-2015-142769
73       Yes  CA-2015-142769
74       Yes  CA-2015-142769
75       Yes  CA-2015-142769
76       Yes  CA-2015-142769
77       Yes  CA-2015-142769
78       Yes  CA-2015-142769
79       Yes  CA-2015-142769
80       Yes  CA-2015-143336
81       Yes  CA-2015-143336
82       Yes  CA-2015-143336
83       Yes  CA-2015-143840
84       Yes  CA-2015-143840
85       Yes  CA-2015-148614
86       Yes  CA-2015-148614
87       Yes  CA-2015-148950
88       Yes  CA-2015-148950
89       Yes  CA-2015-148950
90       Yes  CA-2015-151162
91       Yes  CA-2015-151162
92       Yes  CA-2015-151162
93       Yes  CA-2015-151162
94       Yes  CA-2015-151162
95       Yes  CA-2015-152345
96       Yes  CA-2015-152345
97       Yes  CA-2015-153150
98       Yes  CA-2015-156349
99       Yes  CA-2015-156349
100      Yes  CA-2015-156349
101      Yes  CA-2015-157924
102      Yes  CA-2015-157924
103      Yes  CA-2015-159338
104      Yes  CA-2015-160766
105      Yes  CA-2015-160766
106      Yes  CA-2015-160766
107      Yes  CA-2015-160766
108      Yes  CA-2015-160766
109      Yes  CA-2015-160766
110      Yes  CA-2015-160766
111      Yes  CA-2015-160773
112      Yes  CA-2015-160773
113      Yes  CA-2015-164721
114      Yes  CA-2015-164721
115      Yes  CA-2015-164721
116      Yes  CA-2015-164861
117      Yes  CA-2015-166744
118      Yes  CA-2015-166744
119      Yes  CA-2015-166744
120      Yes  CA-2015-169019
121      Yes  CA-2015-169019
122      Yes  CA-2015-169019
123      Yes  CA-2015-169019
124      Yes  CA-2015-169019
125      Yes  CA-2015-169019
126      Yes  CA-2016-101910
127      Yes  CA-2016-103716
128      Yes  CA-2016-103716
129      Yes  CA-2016-104129
130      Yes  CA-2016-104129
131      Yes  CA-2016-105158
132      Yes  CA-2016-105158
133      Yes  CA-2016-107678
134      Yes  CA-2016-107678
135      Yes  CA-2016-107678
136      Yes  CA-2016-107678
137      Yes  CA-2016-109736
138      Yes  CA-2016-110814
139      Yes  CA-2016-110814
140      Yes  CA-2016-110814
141      Yes  CA-2016-111948
142      Yes  CA-2016-111948
143      Yes  CA-2016-112144
144      Yes  CA-2016-112144
145      Yes  CA-2016-113628
146      Yes  CA-2016-113628
147      Yes  CA-2016-113628
148      Yes  CA-2016-113628
149      Yes  CA-2016-113628
150      Yes  CA-2016-113628
151      Yes  CA-2016-114048
152      Yes  CA-2016-116092
153      Yes  CA-2016-116092
154      Yes  CA-2016-116092
155      Yes  CA-2016-116092
156      Yes  CA-2016-116092
157      Yes  CA-2016-119214
158      Yes  CA-2016-119214
159      Yes  CA-2016-119907
160      Yes  CA-2016-123568
161      Yes  CA-2016-123568
162      Yes  CA-2016-123568
163      Yes  CA-2016-123568
164      Yes  CA-2016-124058
165      Yes  CA-2016-124058
166      Yes  CA-2016-130456
167      Yes  CA-2016-130456
168      Yes  CA-2016-130785
169      Yes  CA-2016-130785
170      Yes  CA-2016-130785
171      Yes  CA-2016-132374
172      Yes  CA-2016-132941
173      Yes  CA-2016-132941
174      Yes  CA-2016-132941
175      Yes  CA-2016-134075
176      Yes  CA-2016-134075
177      Yes  CA-2016-134201
178      Yes  CA-2016-134201
179      Yes  CA-2016-135580
180      Yes  CA-2016-135580
181      Yes  CA-2016-135580
182      Yes  CA-2016-135580
183      Yes  CA-2016-135580
184      Yes  CA-2016-138674
185      Yes  CA-2016-138674
186      Yes  CA-2016-138674
187      Yes  CA-2016-139731
188      Yes  CA-2016-139731
189      Yes  CA-2016-140984
190      Yes  CA-2016-140984
191      Yes  CA-2016-140984
192      Yes  CA-2016-141593
193      Yes  CA-2016-141593
194      Yes  CA-2016-141593
195      Yes  CA-2016-141593
196      Yes  CA-2016-142601
197      Yes  CA-2016-142601
198      Yes  CA-2016-143238
199      Yes  CA-2016-143490
200      Yes  CA-2016-143490
201      Yes  CA-2016-143602
202      Yes  CA-2016-144267
203      Yes  CA-2016-144267
204      Yes  CA-2016-144267
205      Yes  CA-2016-144267
206      Yes  CA-2016-146255
207      Yes  CA-2016-146255
208      Yes  CA-2016-146255
209      Yes  CA-2016-146255
210      Yes  CA-2016-146262
211      Yes  CA-2016-146262
212      Yes  CA-2016-146262
213      Yes  CA-2016-146262
214      Yes  CA-2016-146262
215      Yes  CA-2016-146486
216      Yes  CA-2016-146486
217      Yes  CA-2016-146486
218      Yes  CA-2016-146486
219      Yes  CA-2016-148873
220      Yes  CA-2016-148873
221      Yes  CA-2016-149342
222      Yes  CA-2016-149342
223      Yes  CA-2016-149342
224      Yes  CA-2016-149636
225      Yes  CA-2016-149636
226      Yes  CA-2016-149650
227      Yes  CA-2016-150770
228      Yes  CA-2016-150770
229      Yes  CA-2016-150770
230      Yes  CA-2016-150770
231      Yes  CA-2016-150875
232      Yes  CA-2016-150875
233      Yes  CA-2016-151547
234      Yes  CA-2016-153220
235      Yes  CA-2016-154970
236      Yes  CA-2016-155761
237      Yes  CA-2016-155761
238      Yes  CA-2016-156440
239      Yes  CA-2016-157770
240      Yes  CA-2016-157770
241      Yes  CA-2016-157770
242      Yes  CA-2016-157770
243      Yes  CA-2016-157812
244      Yes  CA-2016-157812
245      Yes  CA-2016-157812
246      Yes  CA-2016-161627
247      Yes  CA-2016-162166
248      Yes  CA-2016-162166
249      Yes  CA-2016-164882
250      Yes  CA-2016-164882
251      Yes  CA-2016-164882
252      Yes  CA-2016-164882
253      Yes  CA-2016-164882
254      Yes  CA-2016-164882
255      Yes  CA-2016-164882
256      Yes  CA-2016-164882
257      Yes  CA-2016-164882
258      Yes  CA-2016-168480
259      Yes  CA-2016-168480
260      Yes  CA-2016-168564
261      Yes  CA-2016-168564
262      Yes  CA-2016-168564
263      Yes  CA-2016-169397
264      Yes  CA-2016-169397
265      Yes  CA-2016-169397
266      Yes  CA-2016-169397
267      Yes  CA-2016-169397
268      Yes  CA-2016-169397
269      Yes  CA-2017-104689
270      Yes  CA-2017-105081
271      Yes  CA-2017-105081
272      Yes  CA-2017-105291
273      Yes  CA-2017-105585
274      Yes  CA-2017-105585
275      Yes  CA-2017-106950
276      Yes  CA-2017-106950
277      Yes  CA-2017-106950
278      Yes  CA-2017-106950
279      Yes  CA-2017-106950
280      Yes  CA-2017-106950
281      Yes  CA-2017-109806
282      Yes  CA-2017-109806
283      Yes  CA-2017-109806
284      Yes  CA-2017-109869
285      Yes  CA-2017-109869
286      Yes  CA-2017-109869
287      Yes  CA-2017-109869
288      Yes  CA-2017-109869
289      Yes  CA-2017-111682
290      Yes  CA-2017-111682
291      Yes  CA-2017-111682
292      Yes  CA-2017-111682
293      Yes  CA-2017-111682
294      Yes  CA-2017-111682
295      Yes  CA-2017-111682
296      Yes  CA-2017-112123
297      Yes  CA-2017-112123
298      Yes  CA-2017-112123
299      Yes  CA-2017-112340
300      Yes  CA-2017-113341
301      Yes  CA-2017-114307
302      Yes  CA-2017-114307
303      Yes  CA-2017-114307
304      Yes  CA-2017-114307
305      Yes  CA-2017-114727
306      Yes  CA-2017-114727
307      Yes  CA-2017-114727
308      Yes  CA-2017-114727
309      Yes  CA-2017-114727
310      Yes  CA-2017-115917
311      Yes  CA-2017-115917
312      Yes  CA-2017-116547
313      Yes  CA-2017-116547
314      Yes  CA-2017-116736
315      Yes  CA-2017-116736
316      Yes  CA-2017-116736
317      Yes  CA-2017-118311
318      Yes  CA-2017-118500
319      Yes  CA-2017-118899
320      Yes  CA-2017-120873
321      Yes  CA-2017-123526
322      Yes  CA-2017-124527
323      Yes  CA-2017-126529
324      Yes  CA-2017-126529
325      Yes  CA-2017-126529
326      Yes  CA-2017-126732
327      Yes  CA-2017-126732
328      Yes  CA-2017-126732
329      Yes  CA-2017-126732
330      Yes  CA-2017-126732
331      Yes  CA-2017-126732
332      Yes  CA-2017-128671
333      Yes  CA-2017-128671
334      Yes  CA-2017-128671
335      Yes  CA-2017-130477
336      Yes  CA-2017-130477
337      Yes  CA-2017-130477
338      Yes  CA-2017-130638
339      Yes  CA-2017-130638
340      Yes  CA-2017-130680
341      Yes  CA-2017-133319
342      Yes  CA-2017-133368
343      Yes  CA-2017-133368
344      Yes  CA-2017-133802
345      Yes  CA-2017-134775
346      Yes  CA-2017-134775
347      Yes  CA-2017-134803
348      Yes  CA-2017-134803
349      Yes  CA-2017-134803
350      Yes  CA-2017-134803
351      Yes  CA-2017-134803
352      Yes  CA-2017-136483
353      Yes  CA-2017-136924
354      Yes  CA-2017-138282
355      Yes  CA-2017-139269
356      Yes  CA-2017-139269
357      Yes  CA-2017-139269
358      Yes  CA-2017-142398
359      Yes  CA-2017-142398
360      Yes  CA-2017-145261
361      Yes  CA-2017-145261
362      Yes  CA-2017-145261
363      Yes  CA-2017-145261
364      Yes  CA-2017-145261
365      Yes  CA-2017-145261
366      Yes  CA-2017-145261
367      Yes  CA-2017-145492
368      Yes  CA-2017-145583
369      Yes  CA-2017-145583
370      Yes  CA-2017-145583
371      Yes  CA-2017-145583
372      Yes  CA-2017-145583
373      Yes  CA-2017-145583
374      Yes  CA-2017-145583
375      Yes  CA-2017-145919
376      Yes  CA-2017-145919
377      Yes  CA-2017-145919
378      Yes  CA-2017-145982
379      Yes  CA-2017-145982
380      Yes  CA-2017-145982
381      Yes  CA-2017-145982
382      Yes  CA-2017-145982
383      Yes  CA-2017-145982
384      Yes  CA-2017-147375
385      Yes  CA-2017-147375
386      Yes  CA-2017-148796
387      Yes  CA-2017-150077
388      Yes  CA-2017-151323
389      Yes  CA-2017-151372
390      Yes  CA-2017-151372
391      Yes  CA-2017-151372
392      Yes  CA-2017-152814
393      Yes  CA-2017-157280
394      Yes  CA-2017-157280
395      Yes  CA-2017-157280
396      Yes  CA-2017-159023
397      Yes  CA-2017-159023
398      Yes  CA-2017-159212
399      Yes  CA-2017-159212
400      Yes  CA-2017-159345
401      Yes  CA-2017-161746
402      Yes  CA-2017-161746
403      Yes  CA-2017-161746
404      Yes  CA-2017-161746
405      Yes  CA-2017-162138
406      Yes  CA-2017-162138
407      Yes  CA-2017-162159
408      Yes  CA-2017-165330
409      Yes  CA-2017-165330
410      Yes  CA-2017-165330
411      Yes  CA-2017-165330
412      Yes  CA-2017-165330
413      Yes  CA-2017-165330
414      Yes  CA-2017-165330
415      Yes  CA-2017-165330
416      Yes  CA-2017-165330
417      Yes  CA-2017-165330
418      Yes  CA-2017-165330
419      Yes  CA-2017-166275
420      Yes  CA-2017-167759
421      Yes  CA-2017-168921
422      Yes  CA-2018-100111
423      Yes  CA-2018-100111
424      Yes  CA-2018-100111
425      Yes  CA-2018-100111
426      Yes  CA-2018-100111
427      Yes  CA-2018-100111
428      Yes  CA-2018-100111
429      Yes  CA-2018-100111
430      Yes  CA-2018-100111
431      Yes  CA-2018-100111
432      Yes  CA-2018-100111
433      Yes  CA-2018-100111
434      Yes  CA-2018-100111
435      Yes  CA-2018-100111
436      Yes  CA-2018-101273
437      Yes  CA-2018-101574
438      Yes  CA-2018-101700
439      Yes  CA-2018-101700
440      Yes  CA-2018-101805
441      Yes  CA-2018-101805
442      Yes  CA-2018-101805
443      Yes  CA-2018-102519
444      Yes  CA-2018-102519
445      Yes  CA-2018-103380
446      Yes  CA-2018-103380
447      Yes  CA-2018-103380
448      Yes  CA-2018-103380
449      Yes  CA-2018-103380
450      Yes  CA-2018-107825
451      Yes  CA-2018-107825
452      Yes  CA-2018-107825
453      Yes  CA-2018-107825
454      Yes  CA-2018-108294
455      Yes  CA-2018-108931
456      Yes  CA-2018-108931
457      Yes  CA-2018-109085
458      Yes  CA-2018-109085
459      Yes  CA-2018-109085
460      Yes  CA-2018-109085
461      Yes  CA-2018-109085
462      Yes  CA-2018-111556
463      Yes  CA-2018-111556
464      Yes  CA-2018-111556
465      Yes  CA-2018-111556
466      Yes  CA-2018-112725
467      Yes  CA-2018-112725
468      Yes  CA-2018-112725
469      Yes  CA-2018-112753
470      Yes  CA-2018-112753
471      Yes  CA-2018-112865
472      Yes  CA-2018-113670
473      Yes  CA-2018-113670
474      Yes  CA-2018-115427
475      Yes  CA-2018-115427
476      Yes  CA-2018-115994
477      Yes  CA-2018-115994
478      Yes  CA-2018-117212
479      Yes  CA-2018-117212
480      Yes  CA-2018-117212
481      Yes  CA-2018-117212
482      Yes  CA-2018-117212
483      Yes  CA-2018-117513
484      Yes  CA-2018-117926
485      Yes  CA-2018-118122
486      Yes  CA-2018-118542
487      Yes  CA-2018-118542
488      Yes  CA-2018-119284
489      Yes  CA-2018-119284
490      Yes  CA-2018-119284
491      Yes  CA-2018-119284
492      Yes  CA-2018-119284
493      Yes  CA-2018-119284
494      Yes  CA-2018-119284
495      Yes  CA-2018-121258
496      Yes  CA-2018-121258
497      Yes  CA-2018-121258
498      Yes  CA-2018-121853
499      Yes  CA-2018-121853
500      Yes  CA-2018-121853
501      Yes  CA-2018-122007
502      Yes  CA-2018-122504
503      Yes  CA-2018-122504
504      Yes  CA-2018-123085
505      Yes  CA-2018-123085
506      Yes  CA-2018-123491
507      Yes  CA-2018-123491
508      Yes  CA-2018-123491
509      Yes  CA-2018-123491
510      Yes  CA-2018-123491
511      Yes  CA-2018-123491
512      Yes  CA-2018-124401
513      Yes  CA-2018-124401
514      Yes  CA-2018-127306
515      Yes  CA-2018-127306
516      Yes  CA-2018-127306
517      Yes  CA-2018-127306
518      Yes  CA-2018-127306
519      Yes  CA-2018-128965
520      Yes  CA-2018-128965
521      Yes  CA-2018-128965
522      Yes  CA-2018-128965
523      Yes  CA-2018-128965
524      Yes  CA-2018-128965
525      Yes  CA-2018-129707
526      Yes  CA-2018-130631
527      Yes  CA-2018-130631
528      Yes  CA-2018-131492
529      Yes  CA-2018-131492
530      Yes  CA-2018-131492
531      Yes  CA-2018-131492
532      Yes  CA-2018-131618
533      Yes  CA-2018-131618
534      Yes  CA-2018-131618
535      Yes  CA-2018-131807
536      Yes  CA-2018-131807
537      Yes  CA-2018-131807
538      Yes  CA-2018-131807
539      Yes  CA-2018-131807
540      Yes  CA-2018-131807
541      Yes  CA-2018-131828
542      Yes  CA-2018-131828
543      Yes  CA-2018-132346
544      Yes  CA-2018-134194
545      Yes  CA-2018-134194
546      Yes  CA-2018-134194
547      Yes  CA-2018-134194
548      Yes  CA-2018-134194
549      Yes  CA-2018-135692
550      Yes  CA-2018-135692
551      Yes  CA-2018-136308
552      Yes  CA-2018-136539
553      Yes  CA-2018-136539
554      Yes  CA-2018-136651
555      Yes  CA-2018-136651
556      Yes  CA-2018-136651
557      Yes  CA-2018-137085
558      Yes  CA-2018-137099
559      Yes  CA-2018-137414
560      Yes  CA-2018-137414
561      Yes  CA-2018-137428
562      Yes  CA-2018-137428
563      Yes  CA-2018-137428
564      Yes  CA-2018-137428
565      Yes  CA-2018-138163
566      Yes  CA-2018-140053
567      Yes  CA-2018-140151
568      Yes  CA-2018-140151
569      Yes  CA-2018-140151
570      Yes  CA-2018-140186
571      Yes  CA-2018-140186
572      Yes  CA-2018-140186
573      Yes  CA-2018-140186
574      Yes  CA-2018-140186
575      Yes  CA-2018-140585
576      Yes  CA-2018-140585
577      Yes  CA-2018-140585
578      Yes  CA-2018-140963
579      Yes  CA-2018-140963
580      Yes  CA-2018-140963
581      Yes  CA-2018-141929
582      Yes  CA-2018-141929
583      Yes  CA-2018-141929
584      Yes  CA-2018-142328
585      Yes  CA-2018-142342
586      Yes  CA-2018-142342
587      Yes  CA-2018-142342
588      Yes  CA-2018-142342
589      Yes  CA-2018-142867
590      Yes  CA-2018-142867
591      Yes  CA-2018-142888
592      Yes  CA-2018-143084
593      Yes  CA-2018-143084
594      Yes  CA-2018-144064
595      Yes  CA-2018-144064
596      Yes  CA-2018-144064
597      Yes  CA-2018-145128
598      Yes  CA-2018-145772
599      Yes  CA-2018-145772
600      Yes  CA-2018-145772
601      Yes  CA-2018-147452
602      Yes  CA-2018-147452
603      Yes  CA-2018-147452
604      Yes  CA-2018-150609
605      Yes  CA-2018-150910
606      Yes  CA-2018-150910
607      Yes  CA-2018-150910
608      Yes  CA-2018-150910
609      Yes  CA-2018-150910
610      Yes  CA-2018-152660
611      Yes  CA-2018-153822
612      Yes  CA-2018-153822
613      Yes  CA-2018-153822
614      Yes  CA-2018-153822
615      Yes  CA-2018-154074
616      Yes  CA-2018-154074
617      Yes  CA-2018-154214
618      Yes  CA-2018-154949
619      Yes  CA-2018-155712
620      Yes  CA-2018-156391
621      Yes  CA-2018-156958
622      Yes  CA-2018-156958
623      Yes  CA-2018-156958
624      Yes  CA-2018-156958
625      Yes  CA-2018-156958
626      Yes  CA-2018-157196
627      Yes  CA-2018-158729
628      Yes  CA-2018-159954
629      Yes  CA-2018-161459
630      Yes  CA-2018-161459
631      Yes  CA-2018-161557
632      Yes  CA-2018-161956
633      Yes  CA-2018-161956
634      Yes  CA-2018-161956
635      Yes  CA-2018-161956
636      Yes  CA-2018-161956
637      Yes  CA-2018-161956
638      Yes  CA-2018-161956
639      Yes  CA-2018-161956
640      Yes  CA-2018-162015
641      Yes  CA-2018-162015
642      Yes  CA-2018-165008
643      Yes  CA-2018-165491
644      Yes  CA-2018-166093
645      Yes  CA-2018-166093
646      Yes  CA-2018-166093
647      Yes  CA-2018-166093
648      Yes  CA-2018-166093
649      Yes  CA-2018-166093
650      Yes  CA-2018-166093
651      Yes  CA-2018-166142
652      Yes  CA-2018-166142
653      Yes  CA-2018-166898
654      Yes  CA-2018-166898
655      Yes  CA-2018-167003
656      Yes  CA-2018-167395
657      Yes  CA-2018-167395
658      Yes  CA-2018-167395
659      Yes  CA-2018-168193
660      Yes  CA-2018-168193
661      Yes  CA-2018-169327
662      Yes  CA-2018-169327
663      Yes  CA-2018-169327
664      Yes  CA-2018-169859
665      Yes  CA-2018-169859
666      Yes  CA-2018-169859
667      Yes  CA-2018-169894
668      Yes  CA-2018-169894
669      Yes  US-2015-105137
670      Yes  US-2015-105137
671      Yes  US-2015-138758
672      Yes  US-2015-138758
673      Yes  US-2015-140452
674      Yes  US-2015-140452
675      Yes  US-2015-140452
676      Yes  US-2015-140452
677      Yes  US-2015-140452
678      Yes  US-2015-140452
679      Yes  US-2015-143287
680      Yes  US-2015-143287
681      Yes  US-2015-143287
682      Yes  US-2015-150574
683      Yes  US-2015-150574
684      Yes  US-2015-164406
685      Yes  US-2015-164406
686      Yes  US-2015-164406
687      Yes  US-2015-164406

order_id repeats. This might be due to the fact that an order can contain multiple products, hence when an order is returned, it is recorded as the number of products for that order.

In [52]:
orders[orders['order_id'] == 'CA-2015-100762']

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,postal_code,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit
6314,6315,CA-2015-100762,11/24/2015,11/29/2015,Standard Class,NG-18355,Nat Gilpin,Corporate,United States,Jackson,...,49201,Central,OFF-AR-10000380,Office Supplies,Art,"Hunt PowerHouse Electric Pencil Sharpener, Blue",151.92,4,0,45.576
6315,6316,CA-2015-100762,11/24/2015,11/29/2015,Standard Class,NG-18355,Nat Gilpin,Corporate,United States,Jackson,...,49201,Central,OFF-LA-10003930,Office Supplies,Labels,"Dot Matrix Printer Tape Reel Labels, White, 50...",196.62,2,0,96.3438
6316,6317,CA-2015-100762,11/24/2015,11/29/2015,Standard Class,NG-18355,Nat Gilpin,Corporate,United States,Jackson,...,49201,Central,OFF-PA-10001815,Office Supplies,Paper,Xerox 1885,144.12,3,0,69.1776
6317,6318,CA-2015-100762,11/24/2015,11/29/2015,Standard Class,NG-18355,Nat Gilpin,Corporate,United States,Jackson,...,49201,Central,OFF-PA-10004082,Office Supplies,Paper,Adams Telephone Message Book w/Frequently-Call...,15.96,2,0,7.98

And indeed, we find that there are four of these orders, just like how the order_id for this order occurs four times in the returns data. We can further check this for all unique values of order_id in the orders table, to see if it occurs the same number of times in the returns table.

In [53]:
def compare_value_counts(df1, df2, col1, col2, id_name="value"):
    """
    Check whether each unique value in col1 (df1) occurs the same number of
    times as in col2 (df2).

    Parameters
    ----------
    df1, df2 : pd.DataFrame
        The two dataframes to compare.
    col1, col2 : str
        Column names to compare (can differ between df1 and df2).
    id_name : str
        Label to use for the compared column in the output (cosmetic).

    Returns
    -------
    pd.DataFrame
        One row per unique value found in either dataframe, with:
        - count_df1, count_df2 : occurrence counts (0 if missing)
        - match : True if counts are equal
    """
    counts1 = df1[col1].value_counts().rename("count_df1")
    counts2 = df2[col2].value_counts().rename("count_df2")

    comparison = pd.concat([counts1, counts2], axis=1).fillna(0)
    comparison[["count_df1", "count_df2"]] = comparison[["count_df1", "count_df2"]].astype(int)
    comparison["match"] = comparison["count_df1"] == comparison["count_df2"]

    comparison.index.name = id_name
    return comparison.reset_index()

In [54]:
result = compare_value_counts(orders, returns_df, "order_id", "order_id")
result[(result.count_df1 > 0) & (result.count_df2 > 0)]

               value  count_df1  count_df2  match
0     CA-2018-100111         14         14   True
3     CA-2017-165330         11         11   True
9     CA-2016-164882          9          9   True
18    US-2018-118087          8          8   True
22    CA-2018-161956          8          8   True
29    CA-2015-142769          8          8   True
35    CA-2017-111682          7          7   True
36    CA-2017-145583          7          7   True
47    US-2018-109253          7          7   True
50    CA-2015-110786          7          7   True
58    CA-2015-160766          7          7   True
62    CA-2017-145261          7          7   True
63    US-2018-147886          7          7   True
76    CA-2018-166093          7          7   True
79    CA-2018-119284          7          7   True
84    CA-2016-169397          6          6   True
95    CA-2015-126361          6          6   True
98    CA-2018-123491          6          6   True
112   CA-2017-145982          6          6   True
114   CA-2016-113628          6          6   True
122   US-2015-140452          6          6   True
133   CA-2018-128965          6          6   True
138   CA-2017-106950          6          6   True
141   CA-2018-131807          6          6   True
147   CA-2017-126732          6          6   True
152   CA-2015-169019          6          6   True
157   CA-2016-146262          5          5   True
165   CA-2017-109869          5          5   True
166   US-2017-105578          5          5   True
178   CA-2018-117212          5          5   True
179   CA-2017-114727          5          5   True
190   CA-2018-103380          5          5   True
191   CA-2016-116092          5          5   True
213   CA-2017-134803          5          5   True
232   CA-2018-127306          5          5   True
238   CA-2015-151162          5          5   True
240   US-2016-160857          5          5   True
242   CA-2018-140186          5          5   True
247   CA-2016-135580          5          5   True
269   US-2015-164763          5          5   True
278   CA-2018-134194          5          5   True
297   US-2017-144057          5          5   True
298   CA-2018-150910          5          5   True
302   CA-2018-109085          5          5   True
304   CA-2018-156958          5          5   True
308   US-2015-164406          5          5   True
333   US-2017-156986          4          4   True
340   CA-2016-144267          4          4   True
356   CA-2015-127131          4          4   True
396   US-2016-128090          4          4   True
402   CA-2015-126403          4          4   True
409   US-2018-103828          4          4   True
411   CA-2018-137428          4          4   True
413   CA-2016-123568          4          4   True
414   CA-2018-131492          4          4   True
420   CA-2016-157770          4          4   True
443   CA-2015-103940          4          4   True
455   CA-2018-111556          4          4   True
489   CA-2016-146486          4          4   True
498   CA-2018-142342          4          4   True
510   CA-2015-141726          4          4   True
512   CA-2015-102652          4          4   True
519   CA-2015-100762          4          4   True
520   CA-2016-146255          4          4   True
529   US-2018-107888          4          4   True
533   CA-2016-107678          4          4   True
546   CA-2018-153822          4          4   True
552   CA-2016-150770          4          4   True
563   US-2017-157490          4          4   True
602   CA-2017-114307          4          4   True
616   CA-2018-107825          4          4   True
640   CA-2017-161746          4          4   True
647   CA-2016-141593          4          4   True
648   CA-2015-143336          3          3   True
651   CA-2017-109806          3          3   True
671   CA-2018-140963          3          3   True
673   CA-2016-157812          3          3   True
681   US-2017-135720          3          3   True
700   CA-2017-116736          3          3   True
702   CA-2017-130477          3          3   True
714   CA-2017-126529          3          3   True
719   CA-2018-140585          3          3   True
724   CA-2015-127012          3          3   True
731   CA-2017-145919          3          3   True
741   US-2017-108455          3          3   True
747   CA-2015-156349          3          3   True
759   CA-2016-130785          3          3   True
771   CA-2018-144064          3          3   True
773   CA-2015-148950          3          3   True
775   CA-2015-164721          3          3   True
788   US-2017-152051          3          3   True
796   CA-2016-149342          3          3   True
806   CA-2018-131618          3          3   True
828   CA-2016-168564          3          3   True
830   CA-2018-169859          3          3   True
831   CA-2017-139269          3          3   True
837   CA-2017-112123          3          3   True
840   US-2016-137008          3          3   True
855   CA-2015-124688          3          3   True
867   CA-2018-141929          3          3   True
877   CA-2016-140984          3          3   True
898   CA-2018-112725          3          3   True
920   US-2018-105046          3          3   True
943   CA-2017-151372          3          3   True
970   CA-2015-166744          3          3   True
972   CA-2018-147452          3          3   True
1008  CA-2016-138674          3          3   True
1029  CA-2018-145772          3          3   True
1095  US-2017-119046          3          3   True
1099  CA-2018-136651          3          3   True
1151  CA-2018-140151          3          3   True
1160  CA-2017-128671          3          3   True
1163  CA-2015-109918          3          3   True
1165  CA-2016-110814          3          3   True
1190  CA-2018-101805          3          3   True
1195  CA-2017-157280          3          3   True
1200  CA-2016-132941          3          3   True
1211  CA-2018-121853          3          3   True
1233  CA-2018-167395          3          3   True
1240  CA-2018-169327          3          3   True
1247  US-2015-143287          3          3   True
1250  CA-2018-121258          3          3   True
1275  CA-2015-133690          2          2   True
1286  CA-2017-162138          2          2   True
1290  CA-2017-134775          2          2   True
1300  US-2015-150574          2          2   True
1301  CA-2017-147375          2          2   True
1326  CA-2017-115917          2          2   True
1357  CA-2018-102519          2          2   True
1363  CA-2018-136539          2          2   True
1364  US-2018-103247          2          2   True
1366  CA-2017-105585          2          2   True
1370  US-2016-126214          2          2   True
1380  CA-2016-143490          2          2   True
1398  CA-2018-115427          2          2   True
1402  CA-2015-160773          2          2   True
1411  CA-2017-159212          2          2   True
1415  CA-2018-115994          2          2   True
1417  CA-2016-139731          2          2   True
1444  CA-2015-135699          2          2   True
1454  US-2017-131149          2          2   True
1497  CA-2016-155761          2          2   True
1501  CA-2016-119214          2          2   True
1503  CA-2018-122504          2          2   True
1504  CA-2018-166142          2          2   True
1505  CA-2018-124401          2          2   True
1619  CA-2016-168480          2          2   True
1627  CA-2018-135692          2          2   True
1632  CA-2018-131828          2          2   True
1637  CA-2015-123498          2          2   True
1652  CA-2015-143840          2          2   True
1658  US-2016-110569          2          2   True
1670  CA-2018-142867          2          2   True
1685  CA-2018-118542          2          2   True
1705  CA-2018-113670          2          2   True
1710  CA-2018-168193          2          2   True
1751  CA-2016-124058          2          2   True
1756  US-2018-155999          2          2   True
1769  CA-2015-157924          2          2   True
1772  CA-2016-150875          2          2   True
1785  CA-2015-152345          2          2   True
1793  CA-2018-169894          2          2   True
1804  US-2015-138758          2          2   True
1811  CA-2018-112753          2          2   True
1820  CA-2016-104129          2          2   True
1830  CA-2016-130456          2          2   True
1838  CA-2017-116547          2          2   True
1840  CA-2016-142601          2          2   True
1880  CA-2016-162166          2          2   True
1898  US-2018-136679          2          2   True
1907  CA-2016-105158          2          2   True
1928  US-2017-151827          2          2   True
1931  US-2017-127425          2          2   True
1933  CA-2018-130631          2          2   True
1963  CA-2015-148614          2          2   True
1966  US-2017-111528          2          2   True
1970  CA-2017-142398          2          2   True
1971  CA-2015-105270          2          2   True
1973  CA-2015-123225          2          2   True
2001  CA-2016-134201          2          2   True
2017  CA-2016-134075          2          2   True
2028  CA-2018-161459          2          2   True
2038  CA-2018-154074          2          2   True
2046  CA-2015-103744          2          2   True
2055  CA-2018-123085          2          2   True
2056  CA-2016-103716          2          2   True
2061  CA-2017-105081          2          2   True
2088  CA-2016-112144          2          2   True
2108  US-2016-136749          2          2   True
2117  CA-2015-116785          2          2   True
2120  CA-2018-137414          2          2   True
2128  CA-2017-133368          2          2   True
2158  US-2016-136987          2          2   True
2172  CA-2015-134726          2          2   True
2190  CA-2016-149636          2          2   True
2286  CA-2018-162015          2          2   True
2287  CA-2018-101700          2          2   True
2317  US-2017-140172          2          2   True
2322  US-2015-105137          2          2   True
2332  CA-2017-159023          2          2   True
2343  CA-2018-143084          2          2   True
2349  CA-2016-148873          2          2   True
2357  CA-2018-166898          2          2   True
2395  CA-2016-111948          2          2   True
2425  CA-2018-108931          2          2   True
2428  CA-2017-130638          2          2   True
2558  CA-2017-148796          1          1   True
2567  CA-2018-154214          1          1   True
2591  CA-2017-136924          1          1   True
2598  CA-2018-137099          1          1   True
2621  CA-2015-153150          1          1   True
2645  CA-2016-101910          1          1   True
2666  CA-2016-143602          1          1   True
2716  CA-2017-152814          1          1   True
2720  CA-2015-159338          1          1   True
2721  CA-2017-112340          1          1   True
2727  CA-2015-126522          1          1   True
2796  CA-2016-119907          1          1   True
2815  CA-2018-108294          1          1   True
2827  CA-2017-159345          1          1   True
2871  CA-2015-135657          1          1   True
2898  CA-2015-103373          1          1   True
2909  CA-2018-142888          1          1   True
2992  CA-2017-136483          1          1   True
3030  CA-2018-165491          1          1   True
3056  CA-2018-140053          1          1   True
3081  CA-2016-143238          1          1   True
3093  CA-2018-145128          1          1   True
3098  CA-2015-164861          1          1   True
3108  CA-2018-137085          1          1   True
3110  CA-2016-153220          1          1   True
3163  CA-2018-112865          1          1   True
3165  CA-2018-138163          1          1   True
3226  US-2017-114293          1          1   True
3291  CA-2018-136308          1          1   True
3344  CA-2017-130680          1          1   True
3357  CA-2018-158729          1          1   True
3372  CA-2016-156440          1          1   True
3415  CA-2015-140816          1          1   True
3423  CA-2017-167759          1          1   True
3447  CA-2016-132374          1          1   True
3509  CA-2016-154970          1          1   True
3535  CA-2015-123253          1          1   True
3568  CA-2018-167003          1          1   True
3571  CA-2017-120873          1          1   True
3623  CA-2016-109736          1          1   True
3630  CA-2017-123526          1          1   True
3643  CA-2018-132346          1          1   True
3680  CA-2018-117926          1          1   True
3725  CA-2017-151323          1          1   True
3734  CA-2016-161627          1          1   True
3798  CA-2015-104829          1          1   True
3800  CA-2017-145492          1          1   True
3811  CA-2018-129707          1          1   True
3819  CA-2018-101574          1          1   True
3929  CA-2017-133319          1          1   True
3933  CA-2018-159954          1          1   True
3976  CA-2016-151547          1          1   True
3980  CA-2016-114048          1          1   True
3985  CA-2017-133802          1          1   True
3986  CA-2018-152660          1          1   True
4002  CA-2015-111871          1          1   True
4039  US-2017-115952          1          1   True
4058  CA-2018-161557          1          1   True
4064  US-2018-147998          1          1   True
4075  CA-2016-149650          1          1   True
4107  CA-2017-168921          1          1   True
4113  CA-2017-166275          1          1   True
4114  CA-2015-108609          1          1   True
4150  CA-2017-124527          1          1   True
4245  CA-2018-118122          1          1   True
4260  CA-2018-150609          1          1   True
4266  CA-2018-154949          1          1   True
4273  US-2018-151127          1          1   True
4328  CA-2017-138282          1          1   True
4335  CA-2018-157196          1          1   True
4369  CA-2017-118899          1          1   True
4398  CA-2018-156391          1          1   True
4420  US-2018-123834          1          1   True
4457  CA-2018-165008          1          1   True
4568  CA-2015-108861          1          1   True
4617  CA-2018-101273          1          1   True
4631  CA-2018-117513          1          1   True
4635  US-2017-114230          1          1   True
4643  CA-2017-113341          1          1   True
4649  CA-2017-118500          1          1   True
4658  CA-2017-118311          1          1   True
4706  CA-2017-162159          1          1   True
4760  CA-2017-150077          1          1   True
4772  CA-2018-122007          1          1   True
4786  CA-2017-104689          1          1   True
4799  CA-2018-155712          1          1   True
4859  US-2017-148957          1          1   True
4864  CA-2015-100867          1          1   True
4942  CA-2017-105291          1          1   True
4964  CA-2018-142328          1          1   True

Confirming our observations, we drop the duplicates of order_id in returns.

In [55]:
returns_df = returns_df.drop_duplicates(subset='order_id')
returns_df.duplicated().sum()

np.int64(0)

### **Test Functional Dependencies**

In [56]:
def fd_violations(df: pd.DataFrame, lhs, rhs: str) -> int:
    """Number of distinct LHS values that map to more than one RHS value."""
    counts = df.groupby(lhs, dropna=False)[rhs].nunique(dropna=False)
    return int((counts > 1).sum())

In [57]:
from itertools import permutations
#lhs->rhs

def check_all_fds(df: pd.DataFrame) -> pd.DataFrame:
    columns = list(df.columns)
    results = []

    for lhs, rhs in permutations(columns, 2):
        violations = fd_violations(df, lhs, rhs)
        results.append(
            {
                "Determinant": lhs,
                "Dependent": rhs,
                "Violations": violations,
                "Holds": violations == 0,
            }
        )

    return pd.DataFrame(results, columns=["Determinant", "Dependent", "Violations", "Holds"])

In [58]:
# Example
#print("order_id -> customer_id violations:", fd_violations(orders, "order_id", "customer_id"))

# TODO: test every dependency you think might hold, e.g. customer -> segment, product -> category,
#       postal code -> city, city -> state, state -> region, and so on.
#       Build a small table of results (determinant, dependent, violations) to put in your report.

#testing all columns for orders
pd.set_option("display.max_rows", None)
order_dependency_df = check_all_fds(orders)

In [59]:
order_dependency_df[order_dependency_df["Violations"] > 0].sort_values("Violations", ascending=False)

       Determinant      Dependent  Violations  Holds
20        order_id         row_id        2471  False
39        order_id         profit        2471  False
36        order_id          sales        2471  False
35        order_id   product_name        2469  False
32        order_id     product_id        2469  False
34        order_id   sub_category        2346  False
37        order_id       quantity        2237  False
340          sales         row_id        1986  False
341          sales       order_id        1985  False
343          sales      ship_date        1985  False
346          sales  customer_name        1984  False
345          sales    customer_id        1984  False
342          sales     order_date        1984  False
351          sales    postal_code        1971  False
349          sales           city        1921  False
350          sales          state        1790  False
265     product_id    customer_id        1771  False
260     product_id         row_id        1771  False
266     product_id  customer_name        1771  False
261     product_id       order_id        1771  False
262     product_id     order_date        1771  False
263     product_id      ship_date        1770  False
271     product_id    postal_code        1768  False
269     product_id           city        1762  False
326   product_name  customer_name        1759  False
276     product_id          sales        1759  False
322   product_name     order_date        1759  False
320   product_name         row_id        1759  False
321   product_name       order_id        1759  False
325   product_name    customer_id        1759  False
279     product_id         profit        1759  False
323   product_name      ship_date        1758  False
331   product_name    postal_code        1756  False
329   product_name           city        1750  False
270     product_id          state        1748  False
339   product_name         profit        1746  False
336   product_name          sales        1746  False
277     product_id       quantity        1738  False
330   product_name          state        1736  False
337   product_name       quantity        1724  False
33        order_id       category        1717  False
272     product_id         region        1699  False
332   product_name         region        1687  False
400         profit         row_id        1617  False
401         profit       order_id        1616  False
403         profit      ship_date        1616  False
402         profit     order_date        1614  False
405         profit    customer_id        1613  False
406         profit  customer_name        1613  False
267     product_id        segment        1610  False
411         profit    postal_code        1602  False
327   product_name        segment        1598  False
264     product_id      ship_mode        1582  False
324   product_name      ship_mode        1572  False
278     product_id       discount        1562  False
338   product_name       discount        1556  False
409         profit           city        1543  False
352          sales         region        1536  False
347          sales        segment        1446  False
410         profit          state        1401  False
344          sales      ship_mode        1401  False
353          sales     product_id        1262  False
356          sales   product_name        1260  False
359          sales         profit        1220  False
38        order_id       discount        1211  False
75       ship_date   product_name        1208  False
79       ship_date         profit        1208  False
60       ship_date         row_id        1208  False
72       ship_date     product_id        1208  False
76       ship_date          sales        1208  False
74       ship_date   sub_category        1197  False
77       ship_date       quantity        1181  False
412         profit         region        1145  False
40      order_date         row_id        1119  False
56      order_date          sales        1119  False
59      order_date         profit        1119  False
52      order_date     product_id        1119  False
55      order_date   product_name        1119  False
54      order_date   sub_category        1104  False
407         profit        segment        1100  False
404         profit      ship_mode        1094  False
65       ship_date  customer_name        1091  False
64       ship_date    customer_id        1091  False
57      order_date       quantity        1091  False
61       ship_date       order_id        1091  False
70       ship_date    postal_code        1089  False
68       ship_date           city        1086  False
73       ship_date       category        1078  False
69       ship_date          state        1065  False
78       ship_date       discount        1049  False
62       ship_date     order_date        1036  False
41      order_date       order_id        1014  False
50      order_date    postal_code        1013  False
45      order_date  customer_name        1013  False
44      order_date    customer_id        1013  False
71       ship_date         region        1012  False
53      order_date       category        1008  False
48      order_date           city        1006  False
58      order_date       discount         981  False
49      order_date          state         979  False
42      order_date      ship_date         962  False
51      order_date         region         929  False
66       ship_date        segment         923  False
63       ship_date      ship_mode         879  False
46      order_date        segment         876  False
355          sales   sub_category         872  False
43      order_date      ship_mode         835  False
120  customer_name         row_id         788  False
132  customer_name     product_id         788  False
119    customer_id         profit         788  False
139  customer_name         profit         788  False
115    customer_id   product_name         788  False
116    customer_id          sales         788  False
112    customer_id     product_id         788  False
100    customer_id         row_id         788  False
136  customer_name          sales         788  False
135  customer_name   product_name         788  False
117    customer_id       quantity         787  False
137  customer_name       quantity         787  False
134  customer_name   sub_category         786  False
114    customer_id   sub_category         786  False
103    customer_id      ship_date         781  False
123  customer_name      ship_date         781  False
102    customer_id     order_date         781  False
101    customer_id       order_id         781  False
121  customer_name       order_id         781  False
122  customer_name     order_date         781  False
128  customer_name           city         780  False
130  customer_name    postal_code         780  False
108    customer_id           city         780  False
110    customer_id    postal_code         780  False
109    customer_id          state         778  False
129  customer_name          state         778  False
133  customer_name       category         772  False
113    customer_id       category         772  False
111    customer_id         region         766  False
131  customer_name         region         766  False
138  customer_name       discount         765  False
118    customer_id       discount         765  False
124  customer_name      ship_mode         724  False
104    customer_id      ship_mode         724  False
357          sales       quantity         693  False
413         profit     product_id         590  False
416         profit   product_name         589  False
235    postal_code   product_name         553  False
236    postal_code          sales         553  False
239    postal_code         profit         553  False
220    postal_code         row_id         553  False
232    postal_code     product_id         553  False
234    postal_code   sub_category         547  False
237    postal_code       quantity         542  False
233    postal_code       category         507  False
225    postal_code    customer_id         488  False
226    postal_code  customer_name         488  False
222    postal_code     order_date         488  False
221    postal_code       order_id         488  False
223    postal_code      ship_date         488  False
358          sales       discount         475  False
180           city         row_id         461  False
192           city     product_id         461  False
196           city          sales         461  False
195           city   product_name         461  False
199           city         profit         461  False
194           city   sub_category         456  False
197           city       quantity         451  False
193           city       category         418  False
227    postal_code        segment         414  False
354          sales       category         408  False
224    postal_code      ship_mode         404  False
183           city      ship_date         401  False
182           city     order_date         401  False
185           city    customer_id         401  False
186           city  customer_name         401  False
181           city       order_id         401  False
238    postal_code       discount         333  False
187           city        segment         331  False
184           city      ship_mode         321  False
417         profit          sales         299  False
198           city       discount         286  False
415         profit   sub_category         271  False
418         profit       quantity         255  False
419         profit       discount         202  False
414         profit       category         115  False
190           city    postal_code          68  False
189           city          state          57  False
201          state       order_id          48  False
200          state         row_id          48  False
214          state   sub_category          48  False
215          state   product_name          48  False
219          state         profit          48  False
203          state      ship_date          48  False
202          state     order_date          48  False
212          state     product_id          48  False
207          state        segment          48  False
205          state    customer_id          48  False
206          state  customer_name          48  False
217          state       quantity          48  False
216          state          sales          48  False
204          state      ship_mode          47  False
213          state       category          47  False
209          state           city          44  False
210          state    postal_code          44  False
191           city         region          44  False
275     product_id   product_name          32  False
218          state       discount          27  False
309   sub_category           city          17  False
310   sub_category          state          17  False
316   sub_category          sales          17  False
317   sub_category       quantity          17  False
315   sub_category   product_name          17  False
313   sub_category     product_id          17  False
311   sub_category    postal_code          17  False
312   sub_category         region          17  False
319   sub_category         profit          17  False
318   sub_category       discount          17  False
300   sub_category         row_id          17  False
301   sub_category       order_id          17  False
307   sub_category        segment          17  False
306   sub_category  customer_name          17  False
305   sub_category    customer_id          17  False
304   sub_category      ship_mode          17  False
303   sub_category      ship_date          17  False
302   sub_category     order_date          17  False
333   product_name     product_id          16  False
365       quantity    customer_id          14  False
363       quantity      ship_date          14  False
362       quantity     order_date          14  False
379       quantity         profit          14  False
377       quantity          sales          14  False
378       quantity       discount          14  False
364       quantity      ship_mode          14  False
373       quantity     product_id          14  False
372       quantity         region          14  False
371       quantity    postal_code          14  False
370       quantity          state          14  False
360       quantity         row_id          14  False
367       quantity        segment          14  False
366       quantity  customer_name          14  False
361       quantity       order_id          14  False
369       quantity           city          14  False
376       quantity   product_name          14  False
375       quantity   sub_category          14  False
374       quantity       category          14  False
384       discount      ship_mode          12  False
385       discount    customer_id          12  False
383       discount      ship_date          12  False
399       discount         profit          12  False
382       discount     order_date          12  False
398       discount       quantity          12  False
387       discount        segment          12  False
386       discount  customer_name          12  False
389       discount           city          12  False
391       discount    postal_code          12  False
393       discount     product_id          12  False
380       discount         row_id          12  False
396       discount   product_name          12  False
381       discount       order_id          12  False
397       discount          sales          12  False
390       discount          state           9  False
395       discount   sub_category           8  False
392       discount         region           7  False
394       discount       category           7  False
99       ship_mode         profit           4  False
98       ship_mode       discount           4  False
82       ship_mode     order_date           4  False
241         region       order_id           4  False
240         region         row_id           4  False
251         region    postal_code           4  False
250         region          state           4  False
83       ship_mode      ship_date           4  False
259         region         profit           4  False
91       ship_mode         region           4  False
92       ship_mode     product_id           4  False
90       ship_mode    postal_code           4  False
89       ship_mode          state           4  False
86       ship_mode        segment           4  False
88       ship_mode           city           4  False
84       ship_mode    customer_id           4  False
85       ship_mode  customer_name           4  False
95       ship_mode   product_name           4  False
96       ship_mode          sales           4  False
93       ship_mode       category           4  False
94       ship_mode   sub_category           4  False
97       ship_mode       quantity           4  False
256         region          sales           4  False
254         region   sub_category           4  False
255         region   product_name           4  False
81       ship_mode       order_id           4  False
242         region     order_date           4  False
244         region      ship_mode           4  False
243         region      ship_date           4  False
246         region  customer_name           4  False
245         region    customer_id           4  False
258         region       discount           4  False
257         region       quantity           4  False
247         region        segment           4  False
249         region           city           4  False
80       ship_mode         row_id           4  False
253         region       category           4  False
252         region     product_id           4  False
299       category         profit           3  False
292       category         region           3  False
293       category     product_id           3  False
148        segment           city           3  False
152        segment     product_id           3  False
145        segment    customer_id           3  False
298       category       discount           3  False
283       category      ship_date           3  False
282       category     order_date           3  False
290       category          state           3  False
289       category           city           3  False
287       category        segment           3  False
286       category  customer_name           3  False
285       category    customer_id           3  False
284       category      ship_mode           3  False
281       category       order_id           3  False
280       category         row_id           3  False
297       category       quantity           3  False
291       category    postal_code           3  False
296       category          sales           3  False
295       category   product_name           3  False
294       category   sub_category           3  False
157        segment       quantity           3  False
159        segment         profit           3  False
158        segment       discount           3  False
146        segment  customer_name           3  False
156        segment          sales           3  False
154        segment   sub_category           3  False
153        segment       category           3  False
151        segment         region           3  False
144        segment      ship_mode           3  False
143        segment      ship_date           3  False
142        segment     order_date           3  False
141        segment       order_id           3  False
140        segment         row_id           3  False
155        segment   product_name           3  False
150        segment    postal_code           3  False
149        segment          state           3  False
229    postal_code           city           1  False
173        country       category           1  False
172        country     product_id           1  False
164        country      ship_mode           1  False
165        country    customer_id           1  False
175        country   product_name           1  False
174        country   sub_category           1  False
166        country  customer_name           1  False
167        country        segment           1  False
168        country           city           1  False
169        country          state           1  False
170        country    postal_code           1  False
171        country         region           1  False
178        country       discount           1  False
179        country         profit           1  False
176        country          sales           1  False
177        country       quantity           1  False
160        country         row_id           1  False
161        country       order_id           1  False
162        country     order_date           1  False
163        country      ship_date           1  False

In [60]:
#reset display max rows
pd.reset_option("display.max_rows")

### **Check ID Uniqueness in the orders data**

In [61]:
def check_id_uniqueness(df: pd.DataFrame) -> pd.DataFrame:
    """Check uniqueness of every column whose name contains 'ID'.

    Columns are matched if their name contains 'ID' (case-insensitive). A
    column is considered unique when it has no duplicate non-null values.
    'n duplicates' counts the number of extra occurrences beyond the first,
    i.e. total rows minus the number of distinct non-null values.

    Returns a DataFrame with columns: "column name", "unique", "n duplicates".
    """
    id_cols = [col for col in df.columns if "id" in str(col).lower()]

    results = []
    for col in id_cols:
        non_null = df[col].dropna()
        n_duplicates = int(non_null.duplicated().sum())
        results.append(
            {
                "column name": col,
                "unique": n_duplicates == 0,
                "n duplicates": n_duplicates,
            }
        )

    return pd.DataFrame(
        results, columns=["column name", "unique", "n duplicates"]
    )

In [62]:
check_id_uniqueness(orders)

   column name  unique  n duplicates
0       row_id    True             0
1     order_id   False          4985
2  customer_id   False          9201
3   product_id   False          8132

The criteria for the helper function used is that the column must simply have 'id' in the name, however some columns CAN serve as identifiers without explicitly having 'id' in the name such as 'Region' for a normalized database with a Region table (Region is also present in the 'People' table). For such cases, it is manually checked.

In [63]:
# TODO: look for data quality problems before you design anything. For example:
#   - Is (order_id, product_id) unique? What should the order-line key be?
#   - Do all postal codes have 5 digits? Are any missing?
#   - Do all IDs follow the same format?
#   - Does returns.csv contain duplicates?
# The source contains several such problems. Your report must list the ones you found and how you handled them.

### **Checking one-to-one mapping between order_id and order_date**

In some case for the orders table/dataframe, for a row with a value of OrderID, A, its Order Date is B such that if A occurs in one row as the ID, its Date is B. It may repeat but its always A-B for any row A or B occurs in. We can verify this below:

In [64]:
n_ids = orders["order_id"].nunique()
n_dates = orders["order_date"].nunique()
n_pairs = len(orders[["order_id", "order_date"]].drop_duplicates())

print(n_ids == n_dates == n_pairs)

False

In [65]:
print(order_dependency_df[(order_dependency_df["Determinant"] == "order_id")&(order_dependency_df["Dependent"] == "order_date")])
print(order_dependency_df[(order_dependency_df["Determinant"] == "order_date")& (order_dependency_df["Dependent"] == "order_id")])

   Determinant   Dependent  Violations  Holds
21    order_id  order_date           0   True
   Determinant Dependent  Violations  Holds
41  order_date  order_id        1014  False

This turns out to be false, or not true both ways. Every order_id maps to exactly one order_date but some dates have more than one order_id hence a many-to-one relationship between order_id and order_date. Altough trivial, its still worth checking for data integrity.

### **Checking Missing Values**

In [66]:
def report_missing_vals(df: pd.DataFrame) -> pd.DataFrame:
    missing = df.isna().sum()
    report = pd.DataFrame(
        {
            "column": missing.index,
            "missing values": missing.values,
            "percentage": (missing.values / len(df)) * 100,
        }
    )
    return report

In [67]:
report_missing_vals(orders)

           column  missing values  percentage
0          row_id               0         0.0
1        order_id               0         0.0
2      order_date               0         0.0
3       ship_date               0         0.0
4       ship_mode               0         0.0
5     customer_id               0         0.0
6   customer_name               0         0.0
7         segment               0         0.0
8         country               0         0.0
9            city               0         0.0
10          state               0         0.0
11    postal_code               0         0.0
12         region               0         0.0
13     product_id               0         0.0
14       category               0         0.0
15   sub_category               0         0.0
16   product_name               0         0.0
17          sales               0         0.0
18       quantity               0         0.0
19       discount               0         0.0
20         profit               0         0.0

In [68]:
report_missing_vals(returns_df)

     column  missing values  percentage
0  returned               0         0.0
1  order_id               0         0.0

### **Checking Postal Codes**
By definition (from the hint in the instructions), postal codes must be 5-digits.

In [69]:
len(orders[orders["postal_code"].astype(str).str.len() != 5])

449

In [70]:
orders[orders["postal_code"].astype(str).str.len() != 5].T

,185,197,267,298,299,300,301,302,306,307,...,9784,9811,9812,9813,9814,9889,9936,9967,9968,9969
row_id,186,198,268,299,300,301,302,303,307,308,...,9785,9812,9813,9814,9815,9890,9937,9968,9969,9970
order_id,CA-2017-105018,CA-2018-107720,CA-2017-111010,CA-2017-142545,CA-2017-142545,CA-2017-142545,CA-2017-142545,CA-2017-142545,CA-2015-111003,CA-2015-111003,...,CA-2016-149748,CA-2017-117583,CA-2017-117583,CA-2017-117583,CA-2017-117583,CA-2018-166499,CA-2018-132955,CA-2018-153871,CA-2018-153871,CA-2018-153871
order_date,11/28/2017,11/6/2018,1/22/2017,10/28/2017,10/28/2017,10/28/2017,10/28/2017,10/28/2017,6/1/2015,6/1/2015,...,5/31/2016,11/27/2017,11/27/2017,11/27/2017,11/27/2017,3/19/2018,6/24/2018,12/11/2018,12/11/2018,12/11/2018
ship_date,12/2/2017,11/13/2018,1/28/2017,11/3/2017,11/3/2017,11/3/2017,11/3/2017,11/3/2017,6/6/2015,6/6/2015,...,6/2/2016,11/30/2017,11/30/2017,11/30/2017,11/30/2017,3/20/2018,6/28/2018,12/17/2018,12/17/2018,12/17/2018
ship_mode,Standard Class,Standard Class,Standard Class,Standard Class,Standard Class,Standard Class,Standard Class,Standard Class,Standard Class,Standard Class,...,Second Class,First Class,First Class,First Class,First Class,First Class,Standard Class,Standard Class,Standard Class,Standard Class
customer_id,SK-19990,VM-21685,PG-18895,JD-15895,JD-15895,JD-15895,JD-15895,JD-15895,CR-12625,CR-12625,...,EM-13825,CB-12025,CB-12025,CB-12025,CB-12025,VG-21805,SC-20575,RB-19435,RB-19435,RB-19435
customer_name,Sally Knutson,Valerie Mitchum,Paul Gonzalez,Jonathan Doherty,Jonathan Doherty,Jonathan Doherty,Jonathan Doherty,Jonathan Doherty,Corey Roper,Corey Roper,...,Elizabeth Moffitt,Cassandra Brandow,Cassandra Brandow,Cassandra Brandow,Cassandra Brandow,Vivek Grady,Sonia Cooley,Richard Bierner,Richard Bierner,Richard Bierner
segment,Consumer,Home Office,Consumer,Corporate,Corporate,Corporate,Corporate,Corporate,Home Office,Home Office,...,Corporate,Consumer,Consumer,Consumer,Consumer,Corporate,Consumer,Consumer,Consumer,Consumer
country,United States,United States,United States,United States,United States,United States,United States,United States,United States,United States,...,United States,United States,United States,United States,United States,United States,United States,United States,United States,United States
city,Fairfield,Westfield,Morristown,Belleville,Belleville,Belleville,Belleville,Belleville,Lakewood,Lakewood,...,Paterson,East Orange,East Orange,East Orange,East Orange,Lakewood,Cranston,Plainfield,Plainfield,Plainfield
state,Connecticut,New Jersey,New Jersey,New Jersey,New Jersey,New Jersey,New Jersey,New Jersey,New Jersey,New Jersey,...,New Jersey,New Jersey,New Jersey,New Jersey,New Jersey,New Jersey,Rhode Island,New Jersey,New Jersey,New Jersey
postal_code,6824,7090,7960,7109,7109,7109,7109,7109,8701,8701,...,7501,7017,7017,7017,7017,8701,2920,7060,7060,7060
region,East,East,East,East,East,East,East,East,East,East,...,East,East,East,East,East,East,East,East,East,East
product_id,OFF-BI-10001890,OFF-ST-10001414,OFF-FA-10003472,OFF-PA-10002105,OFF-ST-10002756,OFF-PA-10004243,FUR-FU-10001861,OFF-BI-10002706,OFF-BI-10001072,OFF-AR-10002135,...,FUR-FU-10001847,OFF-PA-10001246,OFF-AR-10000658,OFF-PA-10000100,OFF-BI-10004233,OFF-AR-10002467,OFF-BI-10002735,OFF-BI-10004209,OFF-BI-10004600,OFF-AP-10003622
category,Office Supplies,Office Supplies,Office Supplies,Office Supplies,Office Supplies,Office Supplies,Furniture,Office Supplies,Office Supplies,Office Supplies,...,Furniture,Office Supplies,Office Supplies,Office Supplies,Office Supplies,Office Supplies,Office Supplies,Office Supplies,Office Supplies,Office Supplies
sub_category,Binders,Storage,Fasteners,Paper,Storage,Paper,Furnishings,Binders,Binders,Art,...,Furnishings,Paper,Art,Paper,Binders,Art,Binders,Binders,Binders,Appliances
product_name,Avery Poly Binder Pockets,Decoflex Hanging Personal Folder File,Bagged Rubber Bands,Xerox 223,"Tennsco Stur-D-Stor Boltless Shelving, 5 Shelv...",Xerox 1939,"Floodlight Indoor Halogen Bulbs, 1 Bulb per Pa...",Avery Premier Heavy-Duty Binder with Round Loc...,"GBC Clear Cover, 8-1/2 x 11, unpunched, 25 cov...",Boston Heavy-Duty Trimline Electric Pencil Sha...,...,Eldon Image Series Black Desk Accessories,Xerox 215,Newell 324,Xerox 1945,"GBC Pre-Punched Binding Paper, Plastic, White,...",Dixon Ticonderoga Pencils,GBC Prestige Therm-A-Bind Covers,"Fellowes Twister Kit, Gray/Clear, 3/pkg",Ibico Ibimaster 300 Manual Binding System,"Bravo II Megaboss 12-Amp Hard Body Upright, Re..."
sales,7.16,46.26,7.56,32.4,1082.48,56.91,77.6,14.28,45.48,289.2,...,8.28,25.92,34.65,204.95,79.95,8.94,102.93,40.2,735.98,22.75
quantity,2,3,6,5,8,3,4,1,3,6,...,2,4,3,5,5,3,3,5,2,7
discount,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
profit,3.4368,12.0276,0.3024,15.552,10.8248,27.3168,38.024,6.5688,20.9208,83.868,...,2.9808,12.4416,9.702,100.4255,38.376,2.4138,48.3771,18.09,331.191,6.5975

Upon checking, some of the observations where the postal code is 4 digits simply lack a 0 at the start so 6824 -> 06824, which maps to Conneticut. We apply this rule for all 4 digit zip codes

In [71]:
#add a zero to the prefix of all postal_codes where its length is 4
orders["postal_code"] = orders["postal_code"].astype(str).str.zfill(5)

In [72]:
len(orders[orders["postal_code"].astype(str).str.len() != 5])

0

In [73]:
orders.head(21).T

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
row_id,1,2,3,4,5,6,7,8,9,10,...,12,13,14,15,16,17,18,19,20,21
order_id,CA-2017-152156,CA-2017-152156,CA-2017-138688,US-2016-108966,US-2016-108966,CA-2015-115812,CA-2015-115812,CA-2015-115812,CA-2015-115812,CA-2015-115812,...,CA-2015-115812,CA-2018-114412,CA-2017-161389,US-2016-118983,US-2016-118983,CA-2015-105893,CA-2015-167164,CA-2015-143336,CA-2015-143336,CA-2015-143336
order_date,11/8/2017,11/8/2017,6/12/2017,10/11/2016,10/11/2016,6/9/2015,6/9/2015,6/9/2015,6/9/2015,6/9/2015,...,6/9/2015,4/15/2018,12/5/2017,11/22/2016,11/22/2016,11/11/2015,5/13/2015,8/27/2015,8/27/2015,8/27/2015
ship_date,11/11/2017,11/11/2017,6/16/2017,10/18/2016,10/18/2016,6/14/2015,6/14/2015,6/14/2015,6/14/2015,6/14/2015,...,6/14/2015,4/20/2018,12/10/2017,11/26/2016,11/26/2016,11/18/2015,5/15/2015,9/1/2015,9/1/2015,9/1/2015
ship_mode,Second Class,Second Class,Second Class,Standard Class,Standard Class,Standard Class,Standard Class,Standard Class,Standard Class,Standard Class,...,Standard Class,Standard Class,Standard Class,Standard Class,Standard Class,Standard Class,Second Class,Second Class,Second Class,Second Class
customer_id,CG-12520,CG-12520,DV-13045,SO-20335,SO-20335,BH-11710,BH-11710,BH-11710,BH-11710,BH-11710,...,BH-11710,AA-10480,IM-15070,HP-14815,HP-14815,PK-19075,AG-10270,ZD-21925,ZD-21925,ZD-21925
customer_name,Claire Gute,Claire Gute,Darrin Van Huff,Sean O'Donnell,Sean O'Donnell,Brosina Hoffman,Brosina Hoffman,Brosina Hoffman,Brosina Hoffman,Brosina Hoffman,...,Brosina Hoffman,Andrew Allen,Irene Maddox,Harold Pawlan,Harold Pawlan,Pete Kriz,Alejandro Grove,Zuschuss Donatelli,Zuschuss Donatelli,Zuschuss Donatelli
segment,Consumer,Consumer,Corporate,Consumer,Consumer,Consumer,Consumer,Consumer,Consumer,Consumer,...,Consumer,Consumer,Consumer,Home Office,Home Office,Consumer,Consumer,Consumer,Consumer,Consumer
country,United States,United States,United States,United States,United States,United States,United States,United States,United States,United States,...,United States,United States,United States,United States,United States,United States,United States,United States,United States,United States
city,Henderson,Henderson,Los Angeles,Fort Lauderdale,Fort Lauderdale,Los Angeles,Los Angeles,Los Angeles,Los Angeles,Los Angeles,...,Los Angeles,Concord,Seattle,Fort Worth,Fort Worth,Madison,West Jordan,San Francisco,San Francisco,San Francisco
state,Kentucky,Kentucky,California,Florida,Florida,California,California,California,California,California,...,California,North Carolina,Washington,Texas,Texas,Wisconsin,Utah,California,California,California
postal_code,42420,42420,90036,33311,33311,90032,90032,90032,90032,90032,...,90032,28027,98103,76106,76106,53711,84084,94109,94109,94109
region,South,South,West,South,South,West,West,West,West,West,...,West,South,West,Central,Central,Central,West,West,West,West
product_id,FUR-BO-10001798,FUR-CH-10000454,OFF-LA-10000240,FUR-TA-10000577,OFF-ST-10000760,FUR-FU-10001487,OFF-AR-10002833,TEC-PH-10002275,OFF-BI-10003910,OFF-AP-10002892,...,TEC-PH-10002033,OFF-PA-10002365,OFF-BI-10003656,OFF-AP-10002311,OFF-BI-10000756,OFF-ST-10004186,OFF-ST-10000107,OFF-AR-10003056,TEC-PH-10001949,OFF-BI-10002215
category,Furniture,Furniture,Office Supplies,Furniture,Office Supplies,Furniture,Office Supplies,Technology,Office Supplies,Office Supplies,...,Technology,Office Supplies,Office Supplies,Office Supplies,Office Supplies,Office Supplies,Office Supplies,Office Supplies,Technology,Office Supplies
sub_category,Bookcases,Chairs,Labels,Tables,Storage,Furnishings,Art,Phones,Binders,Appliances,...,Phones,Paper,Binders,Appliances,Binders,Storage,Storage,Art,Phones,Binders
product_name,Bush Somerset Collection Bookcase,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",Self-Adhesive Address Labels for Typewriters b...,Bretford CR4500 Series Slim Rectangular Table,Eldon Fold 'N Roll Cart System,Eldon Expressions Wood and Plastic Desk Access...,Newell 322,Mitel 5320 IP Phone VoIP phone,DXL Angle-View Binders with Locking Rings by S...,Belkin F5C206VTEL 6 Outlet Surge,...,Konftel 250 ConferenceÂ phoneÂ - Charcoal black,Xerox 1967,Fellowes PB200 Plastic Comb Binding Machine,Holmes Replacement Filter for HEPA Air Cleaner...,Storex DuraTech Recycled Plastic Frosted Binders,"Stur-D-Stor Shelving, Vertical 5-Shelf: 72""H x...",Fellowes Super Stor/Drawer,Newell 341,Cisco SPA 501G IP Phone,"Wilson Jones Hanging View Binder, White, 1"""
sales,261.96,731.94,14.62,957.5775,22.368,48.86,7.28,907.152,18.504,114.9,...,911.424,15.552,407.976,68.81,2.544,665.88,55.5,8.56,213.48,22.72
quantity,2,3,2,5,2,7,4,6,3,5,...,4,3,3,5,3,6,2,2,3,4
discount,0,0,0,0.45,0.2,0,0,0.2,0.2,0,...,0.2,0.2,0.2,0.8,0.8,0,0,0,0.2,0.2
profit,41.9136,219.582,6.8714,-383.031,2.5164,14.1694,1.9656,90.7152,5.7825,34.47,...,68.3568,5.4432,132.5922,-123.858,-3.816,13.3176,9.99,2.4824,16.011,7.384

In [74]:
#display unique values for categorical columns
print(orders['country'].value_counts())
print('-'*20)
print(orders['ship_mode'].value_counts())
print('-'*20)
print(orders["segment"].value_counts())
print('-'*20)
print(orders["region"].value_counts())
print('-'*20)
print(orders['category'].value_counts())
print('-'*20)
print(orders['sub_category'].value_counts())

country
United States    9994
Name: count, dtype: int64
--------------------
ship_mode
Standard Class    5968
Second Class      1945
First Class       1538
Same Day           543
Name: count, dtype: int64
--------------------
segment
Consumer       5191
Corporate      3020
Home Office    1783
Name: count, dtype: int64
--------------------
region
West       3203
East       2848
Central    2323
South      1620
Name: count, dtype: int64
--------------------
category
Office Supplies    6026
Furniture          2121
Technology         1847
Name: count, dtype: int64
--------------------
sub_category
Binders        1523
Paper          1370
Furnishings     957
Phones          889
Storage         846
Art             796
Accessories     775
Chairs          617
Appliances      466
Labels          364
Tables          319
Envelopes       254
Bookcases       228
Fasteners       217
Supplies        190
Machines        115
Copiers          68
Name: count, dtype: int64

The columns for an orders table must depend on order_id, in other words order_id cannot repeat and is the unique identifier. Other id's (such as customer_id) can repeat but are better referenced from its own table (ideally a customers table).

In [75]:
orders.head().T

,0,1,2,3,4
row_id,1,2,3,4,5
order_id,CA-2017-152156,CA-2017-152156,CA-2017-138688,US-2016-108966,US-2016-108966
order_date,11/8/2017,11/8/2017,6/12/2017,10/11/2016,10/11/2016
ship_date,11/11/2017,11/11/2017,6/16/2017,10/18/2016,10/18/2016
ship_mode,Second Class,Second Class,Second Class,Standard Class,Standard Class
customer_id,CG-12520,CG-12520,DV-13045,SO-20335,SO-20335
customer_name,Claire Gute,Claire Gute,Darrin Van Huff,Sean O'Donnell,Sean O'Donnell
segment,Consumer,Consumer,Corporate,Consumer,Consumer
country,United States,United States,United States,United States,United States
city,Henderson,Henderson,Los Angeles,Fort Lauderdale,Fort Lauderdale
state,Kentucky,Kentucky,California,Florida,Florida
postal_code,42420,42420,90036,33311,33311
region,South,South,West,South,South
product_id,FUR-BO-10001798,FUR-CH-10000454,OFF-LA-10000240,FUR-TA-10000577,OFF-ST-10000760
category,Furniture,Furniture,Office Supplies,Furniture,Office Supplies
sub_category,Bookcases,Chairs,Labels,Tables,Storage
product_name,Bush Somerset Collection Bookcase,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",Self-Adhesive Address Labels for Typewriters b...,Bretford CR4500 Series Slim Rectangular Table,Eldon Fold 'N Roll Cart System
sales,261.96,731.94,14.62,957.5775,22.368
quantity,2,3,2,5,2
discount,0,0,0,0.45,0.2
profit,41.9136,219.582,6.8714,-383.031,2.5164

Checking if quanitity is greater than zero for all rows

In [76]:
len(orders[orders['quantity'].astype(int) > 0]) == len(orders)

True

**Profiling findings** (summarize here, and in more detail in your report)

*TODO: write your findings and the design decision each one leads to.*

## 2. Transform: shared cleaning

Clean the data **once**, then build both warehouses from the same clean staging tables.
That way, any difference between the two warehouses comes from the model, not from the cleaning.

Load your result to `staging.orders_clean`, `staging.returns_clean`, and `staging.people_clean` with proper types.

In [77]:
clean = orders.copy()

In [78]:
# TODO: convert types (dates, numbers), trim text, fix the problems you found in profiling.
#the functions below applies the fixes in the previous step
def clean_orders_table(orders:pd.DataFrame)-> pd.DataFrame:
    # Convert date columns to datetime
    orders['order_date'] = pd.to_datetime(orders['order_date'], errors='coerce')
    orders['ship_date'] = pd.to_datetime(orders['ship_date'], errors='coerce')

    # Convert numeric columns to appropriate types
    orders['quantity'] = pd.to_numeric(orders['quantity'], errors='coerce')
    orders['sales'] = pd.to_numeric(orders['sales'], errors='coerce')
    orders['discount'] = pd.to_numeric(orders['discount'], errors='coerce')
    orders['profit'] = pd.to_numeric(orders['profit'], errors='coerce')

    # Trim whitespace from string columns
    str_cols = orders.select_dtypes(include=['object']).columns
    for col in str_cols:
        orders[col] = orders[col].str.strip()

    # Fix postal code issues (ensure 5 digits)
    orders['postal_code'] = orders['postal_code'].astype(str).str.zfill(5)

    # Check quantity, drop rows where quantity is less than or equal to 0
    if len(orders[orders['quantity'].astype(int) > 0]) != len(orders):
        orders.drop(orders[orders['quantity'].astype(int) <= 0].index, inplace=True)

    # restict segment to either consumer, corporate or home office
    valid_segments = ['Consumer', 'Corporate', 'Home Office']
    orders = orders[orders['segment'].isin(valid_segments)]

    # restrict region to either central, east, south or west
    valid_regions = ['Central', 'East', 'South', 'West']
    orders = orders[orders['region'].isin(valid_regions)]

    #restrict ship_mode to either Standard Class, Second Class, First Class or Same Day
    valid_ship_modes = ['Standard Class', 'Second Class', 'First Class', 'Same Day']
    orders = orders[orders['ship_mode'].isin(valid_ship_modes)]

    # Drop rows with missing critical values (e.g., order_id, product_id)
    orders.dropna(subset=['order_id', 'product_id'], inplace=True)

    return orders

def clean_returns_table(returns_df: pd.DataFrame) -> pd.DataFrame:
    valid_returns = ['Yes', 'No']
    returns_df = returns_df[returns_df['returned'].isin(valid_returns)]

    #map return status to boolean
    returns_df['returned'] = returns_df['returned'].map({'Yes': True, 'No': False})
    returns_df['returned'].astype(bool)

    #drop duplicates
    returns_df = returns_df.drop_duplicates()

    return returns_df 

def clean_people_table(people: pd.DataFrame) -> pd.DataFrame:
    #title case for regional_manager
    people['regional_manager'] = people['regional_manager'].str.title()

    #strip leading whitespaces in regional_manager
    people['regional_manager'] = people['regional_manager'].str.strip()

    #drop duplicates 
    people = people.drop_duplicates()

    #ensure region is within [West, East, Central, South]
    valid_regions = ['West', 'East', 'Central', 'South']
    people = people[people['region'].isin(valid_regions)]

    return people

In [79]:
returns_clean = raw_returns.rename(columns=snake)   # TODO: clean
people_clean  = raw_people.rename(columns=snake)    # TODO: clean

In [80]:
#apply the cleaning step
clean = clean_orders_table(clean)
returns_clean = clean_returns_table(returns_clean)
people = clean_people_table(people_clean)

C:\Users\L\AppData\Local\Temp\ipykernel_18644\979592148.py:15: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  str_cols = orders.select_dtypes(include=['object']).columns

In [81]:
# TODO: add assert statements that stop the pipeline if the data is still invalid
def check_orders_data(clean: pd.DataFrame) -> bool:
    try:
        #row_id uniqueness
        assert clean["row_id"].is_unique 

        #check datatypes
        assert pd.api.types.is_datetime64_any_dtype(clean['order_date']) == True 
        assert pd.api.types.is_datetime64_any_dtype(clean['ship_date']) == True
        assert pd.api.types.is_numeric_dtype(clean['quantity']) == True
        assert pd.api.types.is_numeric_dtype(clean['sales']) == True
        assert pd.api.types.is_numeric_dtype(clean['discount']) == True
        assert pd.api.types.is_numeric_dtype(clean['profit']) == True

        #all postal code entries are 5 digits
        assert len(clean['postal_code'] == 5) == len(clean)

        #quantity must be greater than zero for all rows
        assert len(clean[clean['quantity'].astype(int) > 0]) == len(clean)

        #no missing values 
        assert (clean.isna().sum().sum() == 0) and (clean.isnull().sum().sum() == 0)

        #segment must be either consumer, corporate or home office
        valid_segments = ['Consumer', 'Corporate', 'Home Office']
        assert clean['segment'].isin(valid_segments).all()

        #region must be either central, east, south or west
        valid_regions = ['Central', 'East', 'South', 'West']
        assert clean['region'].isin(valid_regions).all()

        #ship_mode must be either Standard Class, Second Class, First Class or Same Day
        valid_ship_modes = ['Standard Class', 'Second Class', 'First Class', 'Same Day']
        assert clean['ship_mode'].isin(valid_ship_modes).all()

    except AssertionError as e:
        print(e)
        return False
    return True 

def check_returns_data(returns_df: pd.DataFrame) -> bool:
    try:
        assert pd.api.types.is_bool_dtype(returns_df['returned'])
        assert returns_df.duplicated().sum().sum() == 0

    except AssertionError as e:
        print(e)
        return False
    return True

def check_people_data(people:pd.DataFrame) -> bool:
    try:
        assert people.duplicated().sum().sum() == 0
        assert people['region'].isin(['West', 'East', 'Central', 'South']).all()
    except AssertionError as e:
        print(e)
        return False
    return True

In [82]:
print("Orders table check: ", check_orders_data(clean))
print("Returns table check: ", check_returns_data(returns_clean))
print("People table check ", check_people_data(people_clean))

Orders table check:  True
Returns table check:  True
People table check  True

In [83]:
clean.to_csv("clean_orders.csv", index=False)
returns_clean.to_csv("returns_clean.csv", index=False)
people_clean.to_csv("people_clean.csv", index=False)

In [84]:
if check_orders_data(clean) and check_returns_data(returns_clean) and check_people_data(people_clean):
    clean.to_sql("orders_clean", engine, schema="staging", if_exists="replace", index=False,
                dtype={"order_date": sa_types.Date, "ship_date": sa_types.Date, 
                       "quantity": sa_types.SmallInteger, "sales": sa_types.Float, 
                       "discount": sa_types.Float, "profit": sa_types.Float, 
                       "postal_code": sa_types.Integer, "row_id": sa_types.Integer})   # TODO: add the other types
    returns_clean.to_sql("returns_clean", engine, schema="staging", if_exists="replace", index=False)
    people_clean.to_sql("people_clean", engine, schema="staging", if_exists="replace", index=False)

    print(table_counts("staging"))
else:
    print("Data is invalid")

      table_name  row_count
0   orders_clean       9994
1     orders_raw       9994
2   people_clean          4
3     people_raw          4
4  returns_clean        296
5    returns_raw        800

## 3. Inmon architecture: 3NF enterprise warehouse

### 3.1 Physical model (DDL)

Write the `CREATE TABLE` statements for your 3NF model. This DDL implements the physical data model in your report.
Use **at least three PostgreSQL-specific features** and explain each one in the report
(for example identity columns, `CHECK` constraints, `UNIQUE NULLS NOT DISTINCT`, indexes, schemas, comments).

One example table is given so you can see the style. Replace or extend it.

In [85]:
INMON_DDL = r"""
DROP SCHEMA IF EXISTS inmon CASCADE;
CREATE SCHEMA inmon;

CREATE TABLE inmon.segment (
    segment_id   SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    segment_name VARCHAR(20) NOT NULL UNIQUE
);

-- TODO: the rest of your 3NF tables, constraints, and indexes
"""
run_sql(INMON_DDL)

### 3.2 Load the 3NF core

Load parent tables before child tables so that foreign keys resolve.

In [86]:
INMON_LOAD = r"""
INSERT INTO inmon.segment (segment_name)
SELECT DISTINCT segment FROM staging.orders_clean;

-- TODO: load every other table
"""
run_sql(INMON_LOAD)
table_counts("inmon")

  table_name  row_count
0    segment          3

In [87]:
# Reconciliation: prove the warehouse holds exactly what the source holds.
# TODO: change the table and column names to match your model, and add more checks.
checks = {
    # "order lines = source rows": q("SELECT count(*) n FROM inmon.<your_line_table>")["n"][0] == len(clean),
    # "total sales matches": np.isclose(float(q("SELECT sum(sales) s FROM inmon.<your_line_table>")["s"][0]), clean["sales"].sum()),
}
assert all(checks.values()), checks
checks

{}

## 4. Kimball architecture: dimensional model

### 4.1 Declare the model

*TODO: fill in before writing any SQL.*

- **Business process:**
- **Grain (one fact row = ?):**
- **Dimensions:**
- **Facts (measures):**

In [88]:
KIMBALL_DDL = r"""
DROP SCHEMA IF EXISTS kimball CASCADE;
CREATE SCHEMA kimball;

-- TODO: dimension tables, then the fact table, constraints, and indexes
"""
run_sql(KIMBALL_DDL)

### 4.2 Load dimensions, then the fact table

Tip: PostgreSQL's `generate_series()` can build a complete date dimension in a single statement.

In [89]:
KIMBALL_LOAD = r"""
-- TODO: load dimensions first, then the fact table
"""
run_sql(KIMBALL_LOAD)
table_counts("kimball")

ProgrammingError: (psycopg2.ProgrammingError) can't execute an empty query
[SQL:
-- TODO: load dimensions first, then the fact table
]
(Background on this error at: https://sqlalche.me/e/21/f405)

In [ ]:
# TODO: reconciliation checks for the Kimball warehouse (row count, total sales, total profit)

## 5. Same business questions, both warehouses

Answer each question **twice**: once against the Inmon 3NF warehouse (`inmon` schema) and once against
the Kimball model. Both answers must be identical, and they must match the source data.

1. Total sales and profit by region for each year.
2. Return rate (percentage of order lines that belong to a returned order) and returned sales, by product category.
3. Top 5 customers by sales in 2018, with their segment and number of orders.

In [ ]:
Q1_INMON = """
-- TODO
"""
Q1_KIMBALL = """
-- TODO
"""
q1_i, q1_k = q(Q1_INMON), q(Q1_KIMBALL)
# TODO: assert that q1_i and q1_k give the same numbers, and check one of them against pandas on `clean`
q1_k

In [ ]:
Q2_INMON = """
-- TODO
"""
Q2_KIMBALL = """
-- TODO
"""
q2_i, q2_k = q(Q2_INMON), q(Q2_KIMBALL)
# TODO: assert that q2_i and q2_k give the same numbers, and check one of them against pandas on `clean`
q2_k

In [ ]:
Q3_INMON = """
-- TODO
"""
Q3_KIMBALL = """
-- TODO
"""
q3_i, q3_k = q(Q3_INMON), q(Q3_KIMBALL)
# TODO: assert that q3_i and q3_k give the same numbers, and check one of them against pandas on `clean`
q3_k

In [ ]:
def join_count(sql): return len(re.findall(r"\bJOIN\b", sql, flags=re.I))

comparison = pd.DataFrame({
    "question": ["Q1", "Q2", "Q3"],
    "joins_inmon_3NF": [join_count(s) for s in (Q1_INMON, Q2_INMON, Q3_INMON)],
    "joins_kimball": [join_count(s) for s in (Q1_KIMBALL, Q2_KIMBALL, Q3_KIMBALL)],
})
comparison

## 6. Evidence for the report

Export the tables you will show in your report. Screenshots of query results are also fine.
For the ER diagrams of the *resulting* warehouses, you can generate them from the live database with
pgAdmin (ERD Tool), DBeaver, or DataGrip.

In [ ]:
out = Path("report_outputs"); out.mkdir(exist_ok=True)
table_counts("inmon").to_csv(out / "inmon_row_counts.csv", index=False)
table_counts("kimball").to_csv(out / "kimball_row_counts.csv", index=False)
comparison.to_csv(out / "join_comparison.csv", index=False)
# TODO: export anything else you need (sample rows, query results, profiling table)
sorted(p.name for p in out.iterdir())